# **1. Notebook Setup**

## **1.1 Imports**

In [1]:
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import yfinance as yf

## **1.2 Notebook Configuration**

In [2]:
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

RANDOM_STATE = 42

np.random.seed(RANDOM_STATE)

## **1.3 Paths**

In [3]:
PROJECT_ROOT = Path().resolve().parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

OUTPUTS_DIR = PROJECT_ROOT / "outputs"

SRC_DIR = PROJECT_ROOT / "src"

# Add project root to Python path
sys.path.append(str(PROJECT_ROOT))

# **2. Data Pull and Processing**

In [4]:
from src.yfinance_loader import fetch_multiple_companies

### **2.1 Sample pull**

In [5]:
TICKERS = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "META"
]

SLEEP_SECONDS = 1

In [6]:
fetch_log = fetch_multiple_companies(
    tickers=TICKERS,
    output_dir=RAW_DATA_DIR / "yfinance",
    sleep_seconds=SLEEP_SECONDS
)

fetch_log.head()

Fetching AAPL...

Fetching MSFT...

Fetching GOOGL...

Fetching AMZN...

Fetching META...

  ticker   status error
0   AAPL  success  None
1   MSFT  success  None
2  GOOGL  success  None
3   AMZN  success  None
4   META  success  None

Everything looks fine for the sample list

### **2.2 Pull Universe of Tickers**

In [7]:
import signal

class TimeoutException(Exception):
    pass

def timeout_handler(signum, frame):
    raise TimeoutException()

In [8]:
from src.data.ticker_universe import build_us_equity_universe

us_equity_universe = build_us_equity_universe(
    remove_non_operating_securities=True,
    output_path=RAW_DATA_DIR / "ticker_universe" / "us_equity_universe.xlsx",
)

us_equity_universe.head(10)

  Symbol                                       Company Name Exchange
0   ACCS                  ACCESS Newswire Inc. Common Stock     AMEX
1   AEON          AEON Biopharma, Inc. Class A Common Stock     AMEX
2   AGIG      Abundia Global Impact Group Inc. Common stock     AMEX
3    AIB  BlockchAIn Digital Infrastructure, Inc Common ...     AMEX
4   AIRI                  Air Industries Group Common Stock     AMEX
5   AMBO  Ambow Education Holding Ltd. American Deposito...     AMEX
6    AMS     American Shared Hospital Services Common Stock     AMEX
7   AMZE                  Amaze Holdings, Inc. Common Stock     AMEX
8    APT                  Alpha Pro Tech, Ltd. Common Stock     AMEX
9   APUS      Apimeds Pharmaceuticals US, Inc. Common Stock     AMEX

In [9]:
us_equity_universe["Exchange"].value_counts()

Exchange
NASDAQ    3307
NYSE      1857
AMEX       239
Name: count, dtype: int64

Number of company tickers are within the ballpark. Good to preceed

### **2.3 Pull Financials based on Ticker Universe**

In [10]:
us_equity_universe = us_equity_universe[
    ~us_equity_universe["Symbol"].str.contains(r"[.$^]", regex=True, na=False)
].copy()

from src.data.financials_loader import (
    fetch_and_flatten_financials,
    filter_companies_with_positive_revenue,
)

### **2.4 Flatten file**

In [11]:
financials_flat_df, financials_fetch_log = fetch_and_flatten_financials(
    ticker_universe=us_equity_universe,
    output_dir=RAW_DATA_DIR / "yfinance_financials",
    sleep_seconds=0.75,
    save_every=100,
)

financials_flat_df.head()

Fetching financial statements:   0%|          | 0/5354 [00:00<?, ?it/s]

Processed 100 of 5,354 companies...

Processed 200 of 5,354 companies...

Processed 300 of 5,354 companies...

Processed 400 of 5,354 companies...

Processed 500 of 5,354 companies...

Processed 600 of 5,354 companies...

Processed 700 of 5,354 companies...

Processed 800 of 5,354 companies...

Processed 900 of 5,354 companies...

Processed 1,000 of 5,354 companies...

Processed 1,100 of 5,354 companies...

Processed 1,200 of 5,354 companies...

Processed 1,300 of 5,354 companies...

Processed 1,400 of 5,354 companies...

Processed 1,500 of 5,354 companies...

Processed 1,600 of 5,354 companies...

Processed 1,700 of 5,354 companies...

Processed 1,800 of 5,354 companies...

Processed 1,900 of 5,354 companies...

Processed 2,000 of 5,354 companies...

Processed 2,100 of 5,354 companies...

Processed 2,200 of 5,354 companies...

Processed 2,300 of 5,354 companies...

Processed 2,400 of 5,354 companies...

Processed 2,500 of 5,354 companies...

Processed 2,600 of 5,354 companies...

Processed 2,700 of 5,354 companies...

Processed 2,800 of 5,354 companies...

Processed 2,900 of 5,354 companies...

Processed 3,000 of 5,354 companies...

Processed 3,100 of 5,354 companies...

Processed 3,200 of 5,354 companies...

Processed 3,300 of 5,354 companies...

Processed 3,400 of 5,354 companies...

Processed 3,500 of 5,354 companies...

Processed 3,600 of 5,354 companies...

Processed 3,700 of 5,354 companies...

Processed 3,800 of 5,354 companies...

Processed 3,900 of 5,354 companies...

Processed 4,000 of 5,354 companies...

Processed 4,100 of 5,354 companies...

Processed 4,200 of 5,354 companies...

Processed 4,300 of 5,354 companies...

Processed 4,400 of 5,354 companies...

Processed 4,500 of 5,354 companies...

Processed 4,600 of 5,354 companies...

Processed 4,700 of 5,354 companies...

Processed 4,800 of 5,354 companies...

Processed 4,900 of 5,354 companies...

Processed 5,000 of 5,354 companies...

Processed 5,100 of 5,354 companies...

Processed 5,200 of 5,354 companies...

Processed 5,300 of 5,354 companies...

Processed 5,400 of 5,354 companies...

,Symbol,Company Name,Exchange,Income_Tax Effect Of Unusual Items,Income_Tax Rate For Calcs,Income_Normalized EBITDA,Income_Total Unusual Items,Income_Total Unusual Items Excluding Goodwill,Income_Net Income From Continuing Operation Net Minority Interest,Income_Reconciled Depreciation,Income_Reconciled Cost Of Revenue,Income_EBITDA,Income_EBIT,Income_Net Interest Income,Income_Interest Expense,Income_Interest Income,Income_Normalized Income,Income_Net Income From Continuing And Discontinued Operation,Income_Total Expenses,Income_Total Operating Income As Reported,Income_Diluted Average Shares,Income_Basic Average Shares,Income_Diluted EPS,Income_Basic EPS,Income_Diluted NI Availto Com Stockholders,Income_Net Income Common Stockholders,Income_Net Income,Income_Net Income Including Noncontrolling Interests,Income_Net Income Discontinuous Operations,Income_Net Income Continuous Operations,Income_Tax Provision,Income_Pretax Income,Income_Other Income Expense,Income_Other Non Operating Income Expenses,Income_Special Income Charges,Income_Other Special Charges,Income_Impairment Of Capital Assets,Income_Gain On Sale Of Security,Income_Net Non Operating Interest Income Expense,Income_Total Other Finance Cost,Income_Interest Expense Non Operating,Income_Interest Income Non Operating,Income_Operating Income,Income_Operating Expense,Income_Depreciation Amortization Depletion Income Statement,Income_Depreciation And Amortization In Income Statement,Income_Research And Development,Income_Selling General And Administration,Income_Selling And Marketing Expense,Income_General And Administrative Expense,Income_Other Gand A,Income_Gross Profit,Income_Cost Of Revenue,Income_Total Revenue,Income_Operating Revenue,Balance_Treasury Shares Number,Balance_Ordinary Shares Number,Balance_Share Issued,Balance_Net Debt,Balance_Total Debt,Balance_Tangible Book Value,Balance_Invested Capital,Balance_Working Capital,Balance_Net Tangible Assets,Balance_Capital Lease Obligations,Balance_Common Stock Equity,Balance_Total Capitalization,Balance_Total Equity Gross Minority Interest,Balance_Stockholders Equity,Balance_Gains Losses Not Affecting Retained Earnings,Balance_Other Equity Adjustments,Balance_Retained Earnings,Balance_Additional Paid In Capital,Balance_Capital Stock,Balance_Common Stock,Balance_Preferred Stock,Balance_Total Liabilities Net Minority Interest,Balance_Total Non Current Liabilities Net Minority Interest,Balance_Other Non Current Liabilities,Balance_Non Current Deferred Liabilities,Balance_Non Current Deferred Taxes Liabilities,Balance_Long Term Debt And Capital Lease Obligation,Balance_Long Term Capital Lease Obligation,Balance_Long Term Debt,Balance_Current Liabilities,Balance_Other Current Liabilities,Balance_Current Deferred Liabilities,Balance_Current Deferred Revenue,Balance_Current Debt And Capital Lease Obligation,Balance_Current Debt,Balance_Other Current Borrowings,Balance_Current Notes Payable,Balance_Payables And Accrued Expenses,Balance_Current Accrued Expenses,Balance_Payables,Balance_Total Tax Payable,Balance_Income Tax Payable,Balance_Accounts Payable,Balance_Total Assets,Balance_Total Non Current Assets,Balance_Other Non Current Assets,Balance_Non Current Deferred Assets,Balance_Non Current Deferred Taxes Assets,Balance_Goodwill And Other Intangible Assets,Balance_Other Intangible Assets,Balance_Goodwill,Balance_Net PPE,Balance_Accumulated Depreciation,Balance_Gross PPE,Balance_Leases,Balance_Other Properties,Balance_Machinery Furniture Equipment,Balance_Properties,Balance_Current Assets,Balance_Other Current Assets,Balance_Assets Held For Sale Current,Balance_Receivables,Balance_Taxes Receivable,Balance_Accounts Receivable,Balance_Allowance For Doubtful Accounts Receivable,Balance_Gross Accounts Receivable,Balance_Cash Cash Equivalents And Short Term Investments,Balance_Cash And Cash Equivalents,CashFlow_Free Cash Flow,CashFlow_Repurchase Of Capital Stock,CashFlow_Repayment Of Debt,CashFlow_Issuance Of Debt,CashFlow_Capital Expenditure,CashFlow_Interest Paid Supplemental Data,CashFlow_Income Tax Paid Supplemental Data,CashFlow_End Cash Position,CashFlow_Beginning Cash Position,CashFlow_Effect Of Exchange Rate Changes,CashFlow_Changes In Cash,CashFlow_Financing Cash Flow,CashFlow_Cash Flow From Continuing Financing Activities,CashFlow_Net Other Financing Charges,CashFlow_Proceeds From Stock Option Exercised,CashFlow_Net Common Stock Issuance,CashFlow_Common Stock Payments,CashFlow_Net Issuance Payments Of Debt,CashFlow_Net Short Term Debt Issuance,CashFlow_Short Term Debt Payments,CashFlow_Net Long Term Debt Issuance,CashFlow_Long Term Debt Payments,CashFlow_Long Term Debt Issuance,CashFlow_Investing Cash Flow,CashFlow_Cash Flow From Continuing Investing Activities,CashFlow_Net Business Purchase And Sale,CashFlow_Sale Of Business,CashFlow_Purchase Of Business,CashFlow_Net PPE Purchase And Sale,CashFlow_Purchase Of PPE,CashFlow_Capital Expenditure Reported,CashFlow_Operating Cash Flow,CashFlow_Cash From Discontinued Operating Activities,CashFlow_Cash Flow From Continuing Operating Activities,CashFlow_Change In Working Capital,CashFlow_Change In Other Working Capital,CashFlow_Change In Other Current Assets,CashFlow_Change In Payables And Accrued Expense,CashFlow_Change In Accrued Expense,CashFlow_Change In Payable,CashFlow_Change In Account Payable,CashFlow_Change In Tax Payable,CashFlow_Change In Income Tax Payable,CashFlow_Change In Receivables,CashFlow_Changes In Account Receivables,CashFlow_Other Non Cash Items,CashFlow_Stock Based Compensation,CashFlow_Provisionand Write Offof Assets,CashFlow_Asset Impairment Charge,CashFlow_Deferred Tax,CashFlow_Deferred Income Tax,CashFlow_Depreciation Amortization Depletion,CashFlow_Depreciation And Amortization,CashFlow_Operating Gains Losses,CashFlow_Gain Loss On Investment Securities,CashFlow_Gain Loss On Sale Of Business,CashFlow_Net Income From Continuing Operations,Income_Restructuring And Mergern Acquisition,Balance_Minority Interest,Balance_Other Equity Interest,Balance_Treasury Stock,Balance_Preferred Securities Outside Stock Equity,Balance_Derivative Product Liabilities,Balance_Current Capital Lease Obligation,Balance_Pensionand Other Post Retirement Benefit Plans Current,Balance_Buildings And Improvements,Balance_Cash Financial,CashFlow_Issuance Of Capital Stock,CashFlow_Common Stock Issuance,CashFlow_Change In Prepaid Assets,CashFlow_Unrealized Gain Loss On Investment Securities,CashFlow_Depreciation,Income_Minority Interests,Income_Write Off,Income_Other Operating Expenses,Income_Provision For Doubtful Accounts,Balance_Total Partnership Capital,Balance_Limited Partnership Capital,Balance_Long Term Provisions,Balance_Other Payable,Balance_Non Current Prepaid Assets,Balance_Investment Properties,Balance_Construction In Progress,Balance_Prepaid Assets,Balance_Other Receivables,Balance_Notes Receivable,CashFlow_Short Term Debt Issuance,CashFlow_Net Other Investing Changes,CashFlow_Net Investment Purchase And Sale,CashFlow_Sale Of Investment,CashFlow_Net Intangibles Purchase And Sale,CashFlow_Purchase Of Intangibles,CashFlow_Change In Interest Payable,CashFlow_Earnings Losses From Equity Investments,Income_Gain On Sale Of Ppe,Income_Depreciation Income Statement,Balance_Tradeand Other Payables Non Current,Balance_Dueto Related Parties Current,Balance_Loans Receivable,CashFlow_Cash Dividends Paid,CashFlow_Common Stock Dividend Paid,CashFlow_Sale Of PPE,CashFlow_Change In Other Current Liabilities,CashFlow_Gain Loss On Sale Of PPE,Balance_Preferred Shares Number,Balance_Non Current Deferred Revenue,Balance_Current Deferred Taxes Liabilities,Balance_Interest Payable,Balance_Land And Improvements,Balance_Restricted Cash,Balance_Inventory,Balance_Inventories Adjustments Allowances,Balance_Finished Goods,Balance_Work In Process,Balance_Raw Materials,CashFlow_Change In Inventory,Income_Gain On Sale Of Business,Balance_Liabilities Heldfor Sale Non Current,Balance_Line Of Credit,Balance_Duefrom Related Parties Non Current,Balance_Non Current Accounts Receivable,Balance_Receivables Adjustments Allowances,Balance_Duefrom Related Parties Current,Balance_Other Short Term Investments,CashFlow_Other Cash Adjustment Outside Changein Cash,CashFlow_Cash From Discontinued Financing Activities,CashFlow_Cash From Discontinued Investing Activities,CashFlow_Purchase Of Investment,CashFlow_Sale Of Intangibles,CashFlow_Amortization Cash Flow,CashFlow_Amortization Of Intangibles,CashFlow_Net Foreign Currency Exchange Gain Loss,Balance_Current Provisions,Income_Preferred Stock Dividends,Income_Salaries And Wages,Balance_Preferred Stock Equity,Balance_Dividends Payable,Balance_Investments And Advances,Balance_Long Term Equity Investment,Balance_Current Deferred Assets,Balance_Accrued Interest Receivable,CashFlow_Net Preferred Stock Issuance,CashFlow_Preferred Stock Issuance,Income_Earnings From Equity Interest,Balance_Investmentsin Joint Venturesat Cost,Balance_Investmentsin Associatesat Cost,Balance_Other Investments,CashFlow_Interest Paid Cfo,Balance_Investmentin Financial Assets,Balance_Financial Assets Designatedas Fair Value Through Profitor Loss Total,Balance_Hedging Assets Current,Income_Rent Expense Supplemental,Income_Other Taxes,Income_Amortization,Income_Amortization Of Intangibles Income Statement,Income_Rent And Landing Fees,Balance_Non Current Accrued Expenses,Income_Otherunder Preferred Stock Dividend,Income_Insurance And Claims,Balance_Available For Sale Securities,CashFlow_Interest Received Cfi,CashFlow_Taxes Refund Paid,Balance_Other Inventories,CashFlow_Preferred Stock Payments,Income_Average Dilution Earnings,Balance_Financial Assets,CashFlow_Depletion,CashFlow_Dividends Received Cfi,Income_Earnings From Equity Interest Net Of Tax,Income_Occupancy And Equipment,Income_Professional Expense And Contract Services Expense,Income_Other Non Interest Expense,Balance_Cash Cash Equivalents And Federal Funds Sold,CashFlow_Amortization Of Securities,Balance_Non Current Note Receivables,Balance_Foreign Currency Translation Adjustments,Balance_Cash Equivalents,CashFlow_Interest Paid Cff,Balance_Minimum Pension Liabilities,Balance_Employee Benefits,Balance_Non Current Pension And Other Postretirement Benefit Plans,Balance_Defined Pension Benefit,CashFlow_Cash Flow From Discontinued Operation,CashFlow_Dividend Received Cfo,CashFlow_Pension And Employee Benefit Expense,CashFlow_Preferred Stock Dividend Paid,Balance_Dueto Related Parties Non Current,CashFlow_Interest Received Cfo,Balance_Held To Maturity Securities,Balance_Investments In Other Ventures Under Equity Method,Income_Excise Taxes,CashFlow_Net Investment Properties Purchase And Sale,CashFlow_Sale Of Investment Properties,CashFlow_Purchase Of Investment Properties,Balance_Current Deferred Taxes Assets,Balance_Investmentsin Subsidiariesat Cost,CashFlow_Cash Flowsfromusedin Operating Activities Direct,CashFlow_Interest Paid Direct,CashFlow_Classesof Cash Payments,CashFlow_Paymentsto Suppliersfor Goodsand Services,CashFlow_Classesof Cash Receiptsfrom Operating Activities,CashFlow_Other Cash Receiptsfrom Operating Activities,CashFlow_Receiptsfrom Government Grants,CashFlow_Receiptsfrom Customers,Balance_Unrealized Gain Loss,Balance_Trading Securities,Income_Securities Amortization,CashFlow_Excess Tax Benefit From Stock Based Compensation,CashFlow_Change In Dividend Payable,Balance_Fixed Assets Revaluation Reserve,Income_Loss Adjustment Expense,Income_Net Policyholder Benefits And Claims,Income_Policyholder Benefits Gross,Income_Policyholder Benefits Ceded,Balance_Commercial Paper,Income_Net Income From Tax Loss Carryforward,CashFlow_Other Cash Adjustment Inside Changein Cash,Balance_General Partnership Capital,CashFlow_Dividend Paid Cfo,CashFlow_Taxes Refund Paid Direct,CashFlow_Interest Received Direct,Balance_Restricted Common Stock,Income_Net Income Extraordinary,CashFlow_Other Cash Paymentsfrom Operating Activities,CashFlow_Paymentson Behalfof Employees,Income_Depletion Income Statement,CashFlow_Dividends Received Direct,CashFlow_Dividends Paid Direct
0,ACCS,ACCESS Newswire Inc. Common Stock,AMEX,-67650.0,0.205,1372000.0,-330000.0,-330000.0,-1558000.0,2993000.0,4999000.0,1042000.0,-1951000.0,-2000.0,2000.0,NaN,-1295650.0,4291000.0,24240000.0,-1871000.0,3859000.0,3858000.0,1.110000,1.110000,4291000.0,4291000.0,4291000.0,4291000.0,5849000.0,-1558000.0,-395000.0,-1953000.0,-330000.0,NaN,-250000.0,NaN,250000.0,-80000.0,-2000.0,NaN,2000.0,NaN,-1621000.0,18935000.0,2687000.0,2687000.0,2692000.0,13556000.0,6405000.0,7151000.0,7151000.0,17314000.0,5305000.0,22619000.0,22619000.0,NaN,3850435.0,3850435.0,NaN,2873000.0,999000.0,32901000.0,-1116000.0,999000.0,317000.0,30345000.0,32031000.0,30345000.0,30345000.0,-96000.0,-96000.0,5432000.0,25005000.0,4000.0,4000.0,0.0,11647000.0,2109000.0,20000.0,86000.0,86000.0,2003000.0,317000.0,1686000.0,9538000.0,NaN,5265000.0,5265000.0,870000.0,870000.0,870000.0,NaN,3403000.0,1769000.0,1634000.0,133000.0,133000.0,1501000.0,41992000.0,33570000.0,73000.0,3691000.0,3691000.0,29346000.0,10303000.0,19043000.0,460000.0,-669000.0,1129000.0,705000.0,324000.0,100000.0,0.0,8422000.0,1513000.0,0.0,3884000.0,NaN,3884000.0,-1336000.0,5220000.0,3025000.0,3025000.0,366000.0,-163000.0,-13391000.0,NaN,-192000.0,413000.0,2208000.0,3025000.0,4103000.0,110000.0,-1188000.0,-13554000.0,-13554000.0,NaN,NaN,-163000.0,-163000.0,-13391000.0,NaN,NaN,-13391000.0,-13391000.0,NaN,11808000.0,11808000.0,12000000.0,12000000.0,NaN,-20000.0,-20000.0,-172000.0,558000.0,NaN,558000.0,-531000.0,208000.0,512000.0,-171000.0,-401000.0,230000.0,154000.0,76000.0,76000.0,-1080000.0,-1080000.0,17000.0,909000.0,1335000.0,250000.0,188000.0,188000.0,2993000.0,2993000.0,-8894000.0,80000.0,-8974000.0,4291000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AEON,"AEON Biopharma, Inc. Class A Common Stock",AMEX,0.0,0.000,-68658000.0,52434000.0,52434000.0,-39222000.0,78000.0,NaN,-16224000.0,-16302000.0,NaN,NaN,NaN,-91656000.0,-39222000.0,16302000.0,-12803000.0,9921587.0,9921587.0,-3.950000,-3.950000,-39222000.0,-39222000.0,-39222000.0,-39222000.0,NaN,-39222000.0,0.0,-39222000.0,-22920000.0,-75354000.0,3499000.0,NaN,NaN,48935000.0,NaN,NaN,NaN,NaN,-16302000.0,16302000.0,NaN,NaN,4094000.0,12208000.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,12105902.0,12105902.0,31594000.0,35745000.0,-55027000.0,-20427000.0,-3499000.0,-55027000.0,1145000.0,-55027000.0,-20427000.0,-55027000.0,-55027000.0,NaN,NaN,-470819000.0,415783000.0,9000.0,9000.0,NaN,60587000.0,53690000.0,42000.0,NaN,NaN,35493000.0,893000.0,34600000.0,6897000.0,NaN,NaN,NaN,252000.0,NaN,NaN,NaN,3773000.0,2262000.0,1511000.0,569000.0,NaN,942000.0,5560000.0,2162000.0,948000.0,NaN,NaN,NaN,NaN,NaN,1214000.0,-344000.0,1558000.0,66000.0,241000.0,199000.0,0.0,3398000.0,392000.0,NaN,NaN,NaN,NaN,NaN,NaN,3006000.0,3006000.0,-17312000.0,NaN,NaN,0.0,-4000.0,NaN,NaN,3006000.0,13000.0,NaN,2993000.0,20305000.0,20305000.0,1791000.0,NaN,18514000.0,NaN,0.0,NaN,NaN,0.0,NaN,0.0,-4000.0,-4000.0,NaN,NaN,NaN,-4000.0,-4000.0,NaN,-17308000.0,NaN,-17308000.0,-6941000.0,-952000.0,NaN,-7174000.0,-2206000.0,-4968000.0,-4968000.0,NaN,NaN,NaN,NaN,19662000.0,5317000.0,NaN,NaN,NaN,NaN,78000.0,78000.0,3798000.0,3798000.0,NaN,-39222000.0,-3499000.0,NaN,NaN,NaN,NaN,18155000.0,252000.0,2872000.0,1052000.0,NaN,18514000.0,18514000.0,1185000.0,NaN,78000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AGIG,Abundia Global Impact Group Inc. Common stock,AMEX,0.0,0.000,-13714909.0,-14900411.0,-14900411.0,-29452289.0,220016.0,430118.0,-28615320.0,-28835336.0,-3942229.0,625599.0,25370.0,-14551878.0,-29452289.0,11028927.0,-28747387.0,32847237.0,32847237.0,-0.900000,-0.900000,-29452289.0,-29452289.0,-29452289.0,-29460935.0,NaN,-29460935.0,0.0,-29460935.0,-14900411.0,NaN,-14929660.0,13270632.0,544028.0,29249.0,-3942229.0,3342000.0,625599.0,25370.0,-10618295.0,10598809.0,NaN,NaN,752287.0,10584333.0,NaN,10584333.0,10584333.0,-19486.0,430118.0,410632.0,410632.0,NaN,36918281.0,36918281.0,5610215.0,10389975.0,4629972.0,29243253.0,-1043785.0,4629972.0,161139.0,19014417.0,25274691.0,19014417.0,19014417.0,-5314.0,-5314.0,-46055127.0,65037940.0,36918.0,36918.0,NaN,12841012.0,6439464.0,NaN,NaN,NaN,6407216.0,146942.0,6260274.0,6401548.0,NaN,NaN,NaN,3982759.0,3968562.0,NaN,3968562.0,2418789.0,NaN,2418789.0,NaN,NaN,2175672.0,31855429.0,26497666.0,12286.0,NaN,NaN,14384445.0,1398295.0,12986150.0,8733660.0,-627816.0,9361476.0,NaN,8730646.0,NaN,NaN,5357763.0,179209.0,NaN,56925.0,NaN,56925.0,NaN,NaN,4618621.0,4618621.0,-18098917.0,NaN,-6444139.0,13310972.0,-10046859.0,NaN,NaN,4618621.0,525809.0,63613.0,4029199.0,15177110.0,15177110.0,NaN,NaN,8310277.0,NaN,6866833.0,3935000.0,-450000.0,2931833.0,-5994139.0,8925972.0,-3095853.0,-3095853.0,NaN,NaN,NaN,-8660829.0,-8660829.0,NaN,-8052058.0,NaN,-8052058.0,1326843.0,NaN,86805.0,1070681.0,433561.0,637120.0,421359.0,NaN,NaN,181405.0,-24019.0,15846013.0,NaN,0.0,1659028.0,NaN,NaN,220016.0,209065.0,2356977.0,-45965.0,NaN,-29460935.0,NaN,0.0,NaN,NaN,NaN,NaN,14197.0,NaN,NaN,NaN,8310277.0,8310277.0,-12048.0,NaN,NaN,8646.0,1115000.0,-737811.0,0.0,NaN,NaN,32248.0,243117.0,2005025.0,1362250.0,630830.0,503008.0,NaN,NaN,4385000.0,NaN,6951006.0,6951006.0,-1386030.0,-1386030.0,433561.0,1522563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
financials_fetch_log["Status"].value_counts()

Status
Success    5354
Name: count, dtype: int64

### **2.5 Filter and Save**

Here we filter out the companies that have revenue < 0, as most KPI calculations require a valid-positive revenue figure

In [14]:
filtered_financials_df = filter_companies_with_positive_revenue(
    financials_df=financials_flat_df,
    revenue_column="Income_Total Revenue",
)

filtered_financials_df.to_excel(
    INTERIM_DATA_DIR / "financials_positive_revenue.xlsx",
    index=False
)

print(f"Original companies: {len(financials_flat_df):,}")
print(f"Companies with positive revenue: {len(filtered_financials_df):,}")

filtered_financials_df.head()

Original companies: 5,354
Companies with positive revenue: 4,576

,Symbol,Company Name,Exchange,Income_Tax Effect Of Unusual Items,Income_Tax Rate For Calcs,Income_Normalized EBITDA,Income_Total Unusual Items,Income_Total Unusual Items Excluding Goodwill,Income_Net Income From Continuing Operation Net Minority Interest,Income_Reconciled Depreciation,Income_Reconciled Cost Of Revenue,Income_EBITDA,Income_EBIT,Income_Net Interest Income,Income_Interest Expense,Income_Interest Income,Income_Normalized Income,Income_Net Income From Continuing And Discontinued Operation,Income_Total Expenses,Income_Total Operating Income As Reported,Income_Diluted Average Shares,Income_Basic Average Shares,Income_Diluted EPS,Income_Basic EPS,Income_Diluted NI Availto Com Stockholders,Income_Net Income Common Stockholders,Income_Net Income,Income_Net Income Including Noncontrolling Interests,Income_Net Income Discontinuous Operations,Income_Net Income Continuous Operations,Income_Tax Provision,Income_Pretax Income,Income_Other Income Expense,Income_Other Non Operating Income Expenses,Income_Special Income Charges,Income_Other Special Charges,Income_Impairment Of Capital Assets,Income_Gain On Sale Of Security,Income_Net Non Operating Interest Income Expense,Income_Total Other Finance Cost,Income_Interest Expense Non Operating,Income_Interest Income Non Operating,Income_Operating Income,Income_Operating Expense,Income_Depreciation Amortization Depletion Income Statement,Income_Depreciation And Amortization In Income Statement,Income_Research And Development,Income_Selling General And Administration,Income_Selling And Marketing Expense,Income_General And Administrative Expense,Income_Other Gand A,Income_Gross Profit,Income_Cost Of Revenue,Income_Total Revenue,Income_Operating Revenue,Balance_Treasury Shares Number,Balance_Ordinary Shares Number,Balance_Share Issued,Balance_Net Debt,Balance_Total Debt,Balance_Tangible Book Value,Balance_Invested Capital,Balance_Working Capital,Balance_Net Tangible Assets,Balance_Capital Lease Obligations,Balance_Common Stock Equity,Balance_Total Capitalization,Balance_Total Equity Gross Minority Interest,Balance_Stockholders Equity,Balance_Gains Losses Not Affecting Retained Earnings,Balance_Other Equity Adjustments,Balance_Retained Earnings,Balance_Additional Paid In Capital,Balance_Capital Stock,Balance_Common Stock,Balance_Preferred Stock,Balance_Total Liabilities Net Minority Interest,Balance_Total Non Current Liabilities Net Minority Interest,Balance_Other Non Current Liabilities,Balance_Non Current Deferred Liabilities,Balance_Non Current Deferred Taxes Liabilities,Balance_Long Term Debt And Capital Lease Obligation,Balance_Long Term Capital Lease Obligation,Balance_Long Term Debt,Balance_Current Liabilities,Balance_Other Current Liabilities,Balance_Current Deferred Liabilities,Balance_Current Deferred Revenue,Balance_Current Debt And Capital Lease Obligation,Balance_Current Debt,Balance_Other Current Borrowings,Balance_Current Notes Payable,Balance_Payables And Accrued Expenses,Balance_Current Accrued Expenses,Balance_Payables,Balance_Total Tax Payable,Balance_Income Tax Payable,Balance_Accounts Payable,Balance_Total Assets,Balance_Total Non Current Assets,Balance_Other Non Current Assets,Balance_Non Current Deferred Assets,Balance_Non Current Deferred Taxes Assets,Balance_Goodwill And Other Intangible Assets,Balance_Other Intangible Assets,Balance_Goodwill,Balance_Net PPE,Balance_Accumulated Depreciation,Balance_Gross PPE,Balance_Leases,Balance_Other Properties,Balance_Machinery Furniture Equipment,Balance_Properties,Balance_Current Assets,Balance_Other Current Assets,Balance_Assets Held For Sale Current,Balance_Receivables,Balance_Taxes Receivable,Balance_Accounts Receivable,Balance_Allowance For Doubtful Accounts Receivable,Balance_Gross Accounts Receivable,Balance_Cash Cash Equivalents And Short Term Investments,Balance_Cash And Cash Equivalents,CashFlow_Free Cash Flow,CashFlow_Repurchase Of Capital Stock,CashFlow_Repayment Of Debt,CashFlow_Issuance Of Debt,CashFlow_Capital Expenditure,CashFlow_Interest Paid Supplemental Data,CashFlow_Income Tax Paid Supplemental Data,CashFlow_End Cash Position,CashFlow_Beginning Cash Position,CashFlow_Effect Of Exchange Rate Changes,CashFlow_Changes In Cash,CashFlow_Financing Cash Flow,CashFlow_Cash Flow From Continuing Financing Activities,CashFlow_Net Other Financing Charges,CashFlow_Proceeds From Stock Option Exercised,CashFlow_Net Common Stock Issuance,CashFlow_Common Stock Payments,CashFlow_Net Issuance Payments Of Debt,CashFlow_Net Short Term Debt Issuance,CashFlow_Short Term Debt Payments,CashFlow_Net Long Term Debt Issuance,CashFlow_Long Term Debt Payments,CashFlow_Long Term Debt Issuance,CashFlow_Investing Cash Flow,CashFlow_Cash Flow From Continuing Investing Activities,CashFlow_Net Business Purchase And Sale,CashFlow_Sale Of Business,CashFlow_Purchase Of Business,CashFlow_Net PPE Purchase And Sale,CashFlow_Purchase Of PPE,CashFlow_Capital Expenditure Reported,CashFlow_Operating Cash Flow,CashFlow_Cash From Discontinued Operating Activities,CashFlow_Cash Flow From Continuing Operating Activities,CashFlow_Change In Working Capital,CashFlow_Change In Other Working Capital,CashFlow_Change In Other Current Assets,CashFlow_Change In Payables And Accrued Expense,CashFlow_Change In Accrued Expense,CashFlow_Change In Payable,CashFlow_Change In Account Payable,CashFlow_Change In Tax Payable,CashFlow_Change In Income Tax Payable,CashFlow_Change In Receivables,CashFlow_Changes In Account Receivables,CashFlow_Other Non Cash Items,CashFlow_Stock Based Compensation,CashFlow_Provisionand Write Offof Assets,CashFlow_Asset Impairment Charge,CashFlow_Deferred Tax,CashFlow_Deferred Income Tax,CashFlow_Depreciation Amortization Depletion,CashFlow_Depreciation And Amortization,CashFlow_Operating Gains Losses,CashFlow_Gain Loss On Investment Securities,CashFlow_Gain Loss On Sale Of Business,CashFlow_Net Income From Continuing Operations,Income_Restructuring And Mergern Acquisition,Balance_Minority Interest,Balance_Other Equity Interest,Balance_Treasury Stock,Balance_Preferred Securities Outside Stock Equity,Balance_Derivative Product Liabilities,Balance_Current Capital Lease Obligation,Balance_Pensionand Other Post Retirement Benefit Plans Current,Balance_Buildings And Improvements,Balance_Cash Financial,CashFlow_Issuance Of Capital Stock,CashFlow_Common Stock Issuance,CashFlow_Change In Prepaid Assets,CashFlow_Unrealized Gain Loss On Investment Securities,CashFlow_Depreciation,Income_Minority Interests,Income_Write Off,Income_Other Operating Expenses,Income_Provision For Doubtful Accounts,Balance_Total Partnership Capital,Balance_Limited Partnership Capital,Balance_Long Term Provisions,Balance_Other Payable,Balance_Non Current Prepaid Assets,Balance_Investment Properties,Balance_Construction In Progress,Balance_Prepaid Assets,Balance_Other Receivables,Balance_Notes Receivable,CashFlow_Short Term Debt Issuance,CashFlow_Net Other Investing Changes,CashFlow_Net Investment Purchase And Sale,CashFlow_Sale Of Investment,CashFlow_Net Intangibles Purchase And Sale,CashFlow_Purchase Of Intangibles,CashFlow_Change In Interest Payable,CashFlow_Earnings Losses From Equity Investments,Income_Gain On Sale Of Ppe,Income_Depreciation Income Statement,Balance_Tradeand Other Payables Non Current,Balance_Dueto Related Parties Current,Balance_Loans Receivable,CashFlow_Cash Dividends Paid,CashFlow_Common Stock Dividend Paid,CashFlow_Sale Of PPE,CashFlow_Change In Other Current Liabilities,CashFlow_Gain Loss On Sale Of PPE,Balance_Preferred Shares Number,Balance_Non Current Deferred Revenue,Balance_Current Deferred Taxes Liabilities,Balance_Interest Payable,Balance_Land And Improvements,Balance_Restricted Cash,Balance_Inventory,Balance_Inventories Adjustments Allowances,Balance_Finished Goods,Balance_Work In Process,Balance_Raw Materials,CashFlow_Change In Inventory,Income_Gain On Sale Of Business,Balance_Liabilities Heldfor Sale Non Current,Balance_Line Of Credit,Balance_Duefrom Related Parties Non Current,Balance_Non Current Accounts Receivable,Balance_Receivables Adjustments Allowances,Balance_Duefrom Related Parties Current,Balance_Other Short Term Investments,CashFlow_Other Cash Adjustment Outside Changein Cash,CashFlow_Cash From Discontinued Financing Activities,CashFlow_Cash From Discontinued Investing Activities,CashFlow_Purchase Of Investment,CashFlow_Sale Of Intangibles,CashFlow_Amortization Cash Flow,CashFlow_Amortization Of Intangibles,CashFlow_Net Foreign Currency Exchange Gain Loss,Balance_Current Provisions,Income_Preferred Stock Dividends,Income_Salaries And Wages,Balance_Preferred Stock Equity,Balance_Dividends Payable,Balance_Investments And Advances,Balance_Long Term Equity Investment,Balance_Current Deferred Assets,Balance_Accrued Interest Receivable,CashFlow_Net Preferred Stock Issuance,CashFlow_Preferred Stock Issuance,Income_Earnings From Equity Interest,Balance_Investmentsin Joint Venturesat Cost,Balance_Investmentsin Associatesat Cost,Balance_Other Investments,CashFlow_Interest Paid Cfo,Balance_Investmentin Financial Assets,Balance_Financial Assets Designatedas Fair Value Through Profitor Loss Total,Balance_Hedging Assets Current,Income_Rent Expense Supplemental,Income_Other Taxes,Income_Amortization,Income_Amortization Of Intangibles Income Statement,Income_Rent And Landing Fees,Balance_Non Current Accrued Expenses,Income_Otherunder Preferred Stock Dividend,Income_Insurance And Claims,Balance_Available For Sale Securities,CashFlow_Interest Received Cfi,CashFlow_Taxes Refund Paid,Balance_Other Inventories,CashFlow_Preferred Stock Payments,Income_Average Dilution Earnings,Balance_Financial Assets,CashFlow_Depletion,CashFlow_Dividends Received Cfi,Income_Earnings From Equity Interest Net Of Tax,Income_Occupancy And Equipment,Income_Professional Expense And Contract Services Expense,Income_Other Non Interest Expense,Balance_Cash Cash Equivalents And Federal Funds Sold,CashFlow_Amortization Of Securities,Balance_Non Current Note Receivables,Balance_Foreign Currency Translation Adjustments,Balance_Cash Equivalents,CashFlow_Interest Paid Cff,Balance_Minimum Pension Liabilities,Balance_Employee Benefits,Balance_Non Current Pension And Other Postretirement Benefit Plans,Balance_Defined Pension Benefit,CashFlow_Cash Flow From Discontinued Operation,CashFlow_Dividend Received Cfo,CashFlow_Pension And Employee Benefit Expense,CashFlow_Preferred Stock Dividend Paid,Balance_Dueto Related Parties Non Current,CashFlow_Interest Received Cfo,Balance_Held To Maturity Securities,Balance_Investments In Other Ventures Under Equity Method,Income_Excise Taxes,CashFlow_Net Investment Properties Purchase And Sale,CashFlow_Sale Of Investment Properties,CashFlow_Purchase Of Investment Properties,Balance_Current Deferred Taxes Assets,Balance_Investmentsin Subsidiariesat Cost,CashFlow_Cash Flowsfromusedin Operating Activities Direct,CashFlow_Interest Paid Direct,CashFlow_Classesof Cash Payments,CashFlow_Paymentsto Suppliersfor Goodsand Services,CashFlow_Classesof Cash Receiptsfrom Operating Activities,CashFlow_Other Cash Receiptsfrom Operating Activities,CashFlow_Receiptsfrom Government Grants,CashFlow_Receiptsfrom Customers,Balance_Unrealized Gain Loss,Balance_Trading Securities,Income_Securities Amortization,CashFlow_Excess Tax Benefit From Stock Based Compensation,CashFlow_Change In Dividend Payable,Balance_Fixed Assets Revaluation Reserve,Income_Loss Adjustment Expense,Income_Net Policyholder Benefits And Claims,Income_Policyholder Benefits Gross,Income_Policyholder Benefits Ceded,Balance_Commercial Paper,Income_Net Income From Tax Loss Carryforward,CashFlow_Other Cash Adjustment Inside Changein Cash,Balance_General Partnership Capital,CashFlow_Dividend Paid Cfo,CashFlow_Taxes Refund Paid Direct,CashFlow_Interest Received Direct,Balance_Restricted Common Stock,Income_Net Income Extraordinary,CashFlow_Other Cash Paymentsfrom Operating Activities,CashFlow_Paymentson Behalfof Employees,Income_Depletion Income Statement,CashFlow_Dividends Received Direct,CashFlow_Dividends Paid Direct
0,ACCS,ACCESS Newswire Inc. Common Stock,AMEX,-67650.0,0.205,1372000.0,-330000.0,-330000.0,-1558000.0,2993000.0,4999000.0,1042000.0,-1951000.0,-2000.0,2000.0,NaN,-1295650.0,4291000.0,24240000.0,-1871000.0,3859000.0,3858000.0,1.110000,1.110000,4291000.0,4291000.0,4291000.0,4291000.0,5849000.0,-1558000.0,-395000.0,-1953000.0,-330000.0,NaN,-250000.0,NaN,250000.0,-80000.0,-2000.0,NaN,2000.0,NaN,-1621000.0,18935000.0,2687000.0,2687000.0,2692000.0,13556000.0,6405000.0,7151000.0,7151000.0,17314000.0,5305000.0,22619000.0,22619000.0,NaN,3850435.0,3850435.0,NaN,2873000.0,999000.0,32901000.0,-1116000.0,999000.0,317000.0,30345000.0,32031000.0,30345000.0,30345000.0,-96000.0,-96000.0,5432000.0,25005000.0,4000.0,4000.0,0.0,11647000.0,2109000.0,20000.0,86000.0,86000.0,2003000.0,317000.0,1686000.0,9538000.0,NaN,5265000.0,5265000.0,870000.0,870000.0,870000.0,NaN,3403000.0,1769000.0,1634000.0,133000.0,133000.0,1501000.0,41992000.0,33570000.0,73000.0,3691000.0,3691000.0,29346000.0,10303000.0,19043000.0,460000.0,-669000.0,1129000.0,705000.0,324000.0,100000.0,0.0,8422000.0,1513000.0,0.0,3884000.0,NaN,3884000.0,-1336000.0,5220000.0,3025000.0,3025000.0,366000.0,-163000.0,-13391000.0,NaN,-192000.0,413000.0,2208000.0,3025000.0,4103000.0,110000.0,-1188000.0,-13554000.0,-13554000.0,NaN,NaN,-163000.0,-163000.0,-13391000.0,NaN,NaN,-13391000.0,-13391000.0,NaN,11808000.0,11808000.0,12000000.0,12000000.0,NaN,-20000.0,-20000.0,-172000.0,558000.0,NaN,558000.0,-531000.0,208000.0,512000.0,-171000.0,-401000.0,230000.0,154000.0,76000.0,76000.0,-1080000.0,-1080000.0,17000.0,909000.0,1335000.0,250000.0,188000.0,188000.0,2993000.0,2993000.0,-8894000.0,80000.0,-8974000.0,4291000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AGIG,Abundia Global Impact Group Inc. Common stock,AMEX,0.0,0.000,-13714909.0,-14900411.0,-14900411.0,-29452289.0,220016.0,430118.0,-28615320.0,-28835336.0,-3942229.0,625599.0,25370.0,-14551878.0,-29452289.0,11028927.0,-28747387.0,32847237.0,32847237.0,-0.900000,-0.900000,-29452289.0,-29452289.0,-29452289.0,-29460935.0,NaN,-29460935.0,0.0,-29460935.0,-14900411.0,NaN,-14929660.0,13270632.0,544028.0,29249.0,-3942229.0,3342000.0,625599.0,25370.0,-10618295.0,10598809.0,NaN,NaN,752287.0,10584333.0,NaN,10584333.0,10584333.0,-19486.0,430118.0,410632.0,410632.0,NaN,36918281.0,36918281.0,5610215.0,10389975.0,4629972.0,29243253.0,-1043785.0,4629972.0,161139.0,19014417.0,25274691.0,19014417.0,19014417.0,-5314.0,-5314.0,-46055127.0,65037940.0,36918.0,36918.0,NaN,12841012.0,6439464.0,NaN,NaN,NaN,6407216.0,146942.0,6260274.0,6401548.0,NaN,NaN,NaN,3982759.0,3968562.0,NaN,3968562.0,2418789.0,NaN,2418789.0,NaN,NaN,2175672.0,31855429.0,26497666.0,12286.0,NaN,NaN,14384445.0,1398295.0,12986150.0,8733660.0,-627816.0,9361476.0,NaN,8730646.0,NaN,NaN,5357763.0,179209.0,NaN,56925.0,NaN,56925.0,NaN,NaN,4618621.0,4618621.0,-18098917.0,NaN,-6444139.0,13310972.0,-10046859.0,NaN,NaN,4618621.0,525809.0,63613.0,4029199.0,15177110.0,15177110.0,NaN,NaN,8310277.0,NaN,6866833.0,3935000.0,-450000.0,2931833.0,-5994139.0,8925972.0,-3095853.0,-3095853.0,NaN,NaN,NaN,-8660829.0,-8660829.0,NaN,-8052058.0,NaN,-8052058.0,1326843.0,NaN,86805.0,1070681.0,433561.0,637120.0,421359.0,NaN,NaN,181405.0,-24019.0,15846013.0,NaN,0.0,1659028.0,NaN,NaN,220016.0,209065.0,2356977.0,-45965.0,NaN,-29460935.0,NaN,0.0,NaN,NaN,NaN,NaN,14197.0,NaN,NaN,NaN,8310277.0,8310277.0,-12048.0,NaN,NaN,8646.0,1115000.0,-737811.0,0.0,NaN,NaN,32248.0,243117.0,2005025.0,1362250.0,630830.0,503008.0,NaN,NaN,4385000.0,NaN,6951006.0,6951006.0,-1386030.0,-1386030.0,433561.0,1522563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AIB,"BlockchAIn Digital Infrastructure, Inc Common ...",AMEX,0.0,0.000,-103195.0,67714.0,67714.0,-835431.0,862305.0,15001351.0,-35481.0,-897786.0,NaN,NaN,NaN,-903145.0,-835431.0,19414398.0,-897786.0,37646133.0,37646133.0,-0.022192,-0.022192,-835431.0,-835431.0,-835431.0,-835431.0,NaN,-835431.0,NaN,-835431.0,62355.0,-5359.0,67714.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-897786.0,4413047.0,862305.0,862305.0,NaN,3550742.0,NaN,NaN,NaN,3515261.0,15001351.0,18516612.0,18516612.0,NaN,37646133.0,37646133.0,NaN,81712.0,3008145.0,7859281.0,-5258420.0,3008145.0,81712.0,7859281.0,7859281.0,7859281.0,7859281.0,NaN,NaN,7859281.0,0.0,0.0,0.0,0.0,9408235.0,680166.0,NaN,NaN,NaN,0.0,0.0,NaN,8728069.0,1845760.0,2330584.0,2330584.0,81712.0,NaN,NaN,NaN,4470013.0,NaN,4470013.0,NaN,NaN,3304012.0,17267516.0,13797867.0,NaN,NaN,NaN,4851136.0,NaN,4851136.0,8946731.0,-1495908.0,10442639.0,2846345.0,7423705.0,172589.0,0.0,3469649.0,218698.0,0.0,3235686.0,NaN,2152226.0,NaN,NaN,15265.0,15265.0,2297032.0,NaN,NaN,NaN,-38927.0,NaN,NaN,15265.0,131107.0,NaN,-115842.0,-2506729.0,-2506729.0,-485833.0,NaN,3889834.0,NaN,-18750.0,-18750.0,NaN,NaN,NaN,NaN,54928.0,54928.0,NaN,NaN,NaN,93073.0,-38927.0,NaN,2335959.0,NaN,2335959.0,2376799.0,664004.0,-158627.0,1448123.0,NaN,NaN,NaN,NaN,NaN,-1422460.0,-1422460.0,NaN,NaN,NaN,NaN,NaN,NaN,862305.0,862305.0,-67714.0,NaN,NaN,-835431.0,NaN,NaN,NaN,NaN,NaN,NaN,81712.0,NaN,NaN,15265.0,3889834.0,3889834.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1166001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38145.0,NaN,NaN,NaN,NaN,NaN,NaN,67714.0,NaN,680166.0,NaN,1083460.0,-5891980.0,-5891980.0,132000.0,1845759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **3. Final Data Check**

### **3.1 Data Quality**

In [15]:
print(financials_flat_df.shape)
print(filtered_financials_df.shape)

(5354, 351)
(4576, 351)

In [16]:
filtered_financials_df[[
    "Income_Total Revenue"
]].describe()

       Income_Total Revenue
count          4.576000e+03
mean           1.800574e+11
std            3.734056e+12
min            5.500000e+02
25%            6.852400e+07
50%            5.943835e+08
75%            3.379406e+09
max            1.467420e+14

In [18]:
filtered_financials_df.isna().mean().sort_values(ascending=False).head(50)

CashFlow_Dividends Paid Direct                                                  1.000000
Balance_Restricted Common Stock                                                 0.999781
CashFlow_Receiptsfrom Government Grants                                         0.999563
CashFlow_Dividends Received Direct                                              0.999344
Income_Depletion Income Statement                                               0.999126
CashFlow_Paymentson Behalfof Employees                                          0.998907
CashFlow_Change In Dividend Payable                                             0.998689
Balance_General Partnership Capital                                             0.998470
CashFlow_Dividend Paid Cfo                                                      0.998252
Income_Net Income From Tax Loss Carryforward                                    0.998252
CashFlow_Other Cash Paymentsfrom Operating Activities                           0.998033
CashFlow_Other Cash Receiptsfrom Operating Activities                           0.998033
CashFlow_Interest Received Direct                                               0.998033
Income_Net Income Extraordinary                                                 0.997815
CashFlow_Interest Paid Direct                                                   0.997815
CashFlow_Taxes Refund Paid Direct                                               0.997378
CashFlow_Paymentsto Suppliersfor Goodsand Services                              0.997159
Balance_Current Deferred Taxes Assets                                           0.997159
CashFlow_Receiptsfrom Customers                                                 0.996941
CashFlow_Other Cash Adjustment Inside Changein Cash                             0.996941
CashFlow_Classesof Cash Receiptsfrom Operating Activities                       0.996503
Balance_Fixed Assets Revaluation Reserve                                        0.996503
Income_Securities Amortization                                                  0.996503
CashFlow_Cash Flowsfromusedin Operating Activities Direct                       0.996285
CashFlow_Classesof Cash Payments                                                0.996285
Balance_Investmentsin Subsidiariesat Cost                                       0.994974
Balance_Limited Partnership Capital                                             0.994974
Balance_Total Partnership Capital                                               0.994318
Balance_Current Deferred Taxes Liabilities                                      0.993007
CashFlow_Excess Tax Benefit From Stock Based Compensation                       0.992788
CashFlow_Depletion                                                              0.991696
Income_Excise Taxes                                                             0.991040
Income_Policyholder Benefits Ceded                                              0.988636
CashFlow_Cash Flow From Discontinued Operation                                  0.988199
Balance_Unrealized Gain Loss                                                    0.988199
Income_Policyholder Benefits Gross                                              0.986014
Balance_Dueto Related Parties Non Current                                       0.985140
Balance_Trading Securities                                                      0.983173
Balance_Duefrom Related Parties Non Current                                     0.982955
Balance_Minimum Pension Liabilities                                             0.982955
Income_Net Policyholder Benefits And Claims                                     0.977928
Income_Loss Adjustment Expense                                                  0.977928
Balance_Commercial Paper                                                        0.975306
CashFlow_Purchase Of Investment Properties                                      0.970498
CashFlow_Sale Of Investment Properties                                          0.970061
CashFlow_Sale Of Intangibles                                                    0.969187
CashFlow_Cash From Discontinued Financing Activities                            0.969187
CashFlow_Interest Received Cfi                                                  0.968313
Balance_Financial Assets Designatedas Fair Value Through Profitor Loss Total    0.967876
CashFlow_Other Cash Adjustment Outside Changein Cash                            0.967439
dtype: float64

### **3.2 Failure logs**

In [19]:
failed_fetches_df = financials_fetch_log[
    financials_fetch_log["Status"] != "Success"
]

failed_fetches_df.to_excel(
    OUTPUTS_DIR / "failed_yfinance_fetches.xlsx",
    index=False
)

print(f"Failed fetches: {len(failed_fetches_df):,}")

Failed fetches: 0

# Notebook Summary

This notebook constructed the initial U.S. equity universe by combining NASDAQ, NYSE, and AMEX listings from NasdaqTrader. The dataset was cleaned to remove ETFs, test issues, and likely non-operating securities.

Financial statement data was then retrieved from Yahoo Finance using the yfinance library. Income statements, balance sheets, and cash flow statements were flattened into a tabular structure suitable for downstream KPI engineering and machine learning workflows.

Checkpoint saving, logging, and validation procedures were implemented to improve robustness and reproducibility. Finally, companies without valid positive revenue values were filtered out to improve dataset quality for subsequent clustering analysis.