# Objective of This Notebook

The objective of this notebook is to clean, validate, and prepare the structured financial dataset generated in Notebook 1 for downstream KPI engineering and clustering analysis.

This notebook focuses on identifying and handling data quality issues commonly present in financial statement datasets, including missing values, sparse features, inconsistent metrics, and extreme outliers. The preprocessing steps implemented here aim to improve the reliability, interpretability, and stability of the subsequent machine learning workflow.

The final output of this notebook will be a cleaned and modelling-ready financial dataset suitable for KPI calculation, dimensionality reduction, and clustering experiments.

# **1. Notebook Setup**

### **1.1 Imports**

In [1]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

### **1.2 Notebook Configuration**

In [2]:
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

RANDOM_STATE = 42

# Plotting style
plt.style.use("default")

# Figure sizing
plt.rcParams["figure.figsize"] = (12, 6)

### **1.3 Paths**

In [3]:
PROJECT_ROOT = Path().resolve().parent

DATA_DIR = PROJECT_ROOT / "data"

RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

OUTPUTS_DIR = PROJECT_ROOT / "outputs"

SRC_DIR = PROJECT_ROOT / "src"

# Add project root to Python path
sys.path.append(str(PROJECT_ROOT))

# **2. Dataset Overview**

### **2.1 Load Flattened Financial Dataset**

In [4]:
financials_df = pd.read_excel(
    INTERIM_DATA_DIR / "financials_with_metadata.xlsx"
)

print(f"Dataset shape: {financials_df.shape}")

financials_df.head()

Dataset shape: (4576, 360)

,Symbol,Company Name,Exchange,Income_Tax Effect Of Unusual Items,Income_Tax Rate For Calcs,Income_Normalized EBITDA,Income_Total Unusual Items,Income_Total Unusual Items Excluding Goodwill,Income_Net Income From Continuing Operation Net Minority Interest,Income_Reconciled Depreciation,Income_Reconciled Cost Of Revenue,Income_EBITDA,Income_EBIT,Income_Net Interest Income,Income_Interest Expense,Income_Interest Income,Income_Normalized Income,Income_Net Income From Continuing And Discontinued Operation,Income_Total Expenses,Income_Total Operating Income As Reported,Income_Diluted Average Shares,Income_Basic Average Shares,Income_Diluted EPS,Income_Basic EPS,Income_Diluted NI Availto Com Stockholders,Income_Net Income Common Stockholders,Income_Net Income,Income_Net Income Including Noncontrolling Interests,Income_Net Income Discontinuous Operations,Income_Net Income Continuous Operations,Income_Tax Provision,Income_Pretax Income,Income_Other Income Expense,Income_Other Non Operating Income Expenses,Income_Special Income Charges,Income_Other Special Charges,Income_Impairment Of Capital Assets,Income_Gain On Sale Of Security,Income_Net Non Operating Interest Income Expense,Income_Total Other Finance Cost,Income_Interest Expense Non Operating,Income_Interest Income Non Operating,Income_Operating Income,Income_Operating Expense,Income_Depreciation Amortization Depletion Income Statement,Income_Depreciation And Amortization In Income Statement,Income_Research And Development,Income_Selling General And Administration,Income_Selling And Marketing Expense,Income_General And Administrative Expense,Income_Other Gand A,Income_Gross Profit,Income_Cost Of Revenue,Income_Total Revenue,Income_Operating Revenue,Balance_Treasury Shares Number,Balance_Ordinary Shares Number,Balance_Share Issued,Balance_Net Debt,Balance_Total Debt,Balance_Tangible Book Value,Balance_Invested Capital,Balance_Working Capital,Balance_Net Tangible Assets,Balance_Capital Lease Obligations,Balance_Common Stock Equity,Balance_Total Capitalization,Balance_Total Equity Gross Minority Interest,Balance_Stockholders Equity,Balance_Gains Losses Not Affecting Retained Earnings,Balance_Other Equity Adjustments,Balance_Retained Earnings,Balance_Additional Paid In Capital,Balance_Capital Stock,Balance_Common Stock,Balance_Preferred Stock,Balance_Total Liabilities Net Minority Interest,Balance_Total Non Current Liabilities Net Minority Interest,Balance_Other Non Current Liabilities,Balance_Non Current Deferred Liabilities,Balance_Non Current Deferred Taxes Liabilities,Balance_Long Term Debt And Capital Lease Obligation,Balance_Long Term Capital Lease Obligation,Balance_Long Term Debt,Balance_Current Liabilities,Balance_Other Current Liabilities,Balance_Current Deferred Liabilities,Balance_Current Deferred Revenue,Balance_Current Debt And Capital Lease Obligation,Balance_Current Debt,Balance_Other Current Borrowings,Balance_Current Notes Payable,Balance_Payables And Accrued Expenses,Balance_Current Accrued Expenses,Balance_Payables,Balance_Total Tax Payable,Balance_Income Tax Payable,Balance_Accounts Payable,Balance_Total Assets,Balance_Total Non Current Assets,Balance_Other Non Current Assets,Balance_Non Current Deferred Assets,Balance_Non Current Deferred Taxes Assets,Balance_Goodwill And Other Intangible Assets,Balance_Other Intangible Assets,Balance_Goodwill,Balance_Net PPE,Balance_Accumulated Depreciation,Balance_Gross PPE,Balance_Leases,Balance_Other Properties,Balance_Machinery Furniture Equipment,Balance_Properties,Balance_Current Assets,Balance_Other Current Assets,Balance_Assets Held For Sale Current,Balance_Receivables,Balance_Taxes Receivable,Balance_Accounts Receivable,Balance_Allowance For Doubtful Accounts Receivable,Balance_Gross Accounts Receivable,Balance_Cash Cash Equivalents And Short Term Investments,Balance_Cash And Cash Equivalents,CashFlow_Free Cash Flow,CashFlow_Repurchase Of Capital Stock,CashFlow_Repayment Of Debt,CashFlow_Issuance Of Debt,CashFlow_Capital Expenditure,CashFlow_Interest Paid Supplemental Data,CashFlow_Income Tax Paid Supplemental Data,CashFlow_End Cash Position,CashFlow_Beginning Cash Position,CashFlow_Effect Of Exchange Rate Changes,CashFlow_Changes In Cash,CashFlow_Financing Cash Flow,CashFlow_Cash Flow From Continuing Financing Activities,CashFlow_Net Other Financing Charges,CashFlow_Proceeds From Stock Option Exercised,CashFlow_Net Common Stock Issuance,CashFlow_Common Stock Payments,CashFlow_Net Issuance Payments Of Debt,CashFlow_Net Short Term Debt Issuance,CashFlow_Short Term Debt Payments,CashFlow_Net Long Term Debt Issuance,CashFlow_Long Term Debt Payments,CashFlow_Long Term Debt Issuance,CashFlow_Investing Cash Flow,CashFlow_Cash Flow From Continuing Investing Activities,CashFlow_Net Business Purchase And Sale,CashFlow_Sale Of Business,CashFlow_Purchase Of Business,CashFlow_Net PPE Purchase And Sale,CashFlow_Purchase Of PPE,CashFlow_Capital Expenditure Reported,CashFlow_Operating Cash Flow,CashFlow_Cash From Discontinued Operating Activities,CashFlow_Cash Flow From Continuing Operating Activities,CashFlow_Change In Working Capital,CashFlow_Change In Other Working Capital,CashFlow_Change In Other Current Assets,CashFlow_Change In Payables And Accrued Expense,CashFlow_Change In Accrued Expense,CashFlow_Change In Payable,CashFlow_Change In Account Payable,CashFlow_Change In Tax Payable,CashFlow_Change In Income Tax Payable,CashFlow_Change In Receivables,CashFlow_Changes In Account Receivables,CashFlow_Other Non Cash Items,CashFlow_Stock Based Compensation,CashFlow_Provisionand Write Offof Assets,CashFlow_Asset Impairment Charge,CashFlow_Deferred Tax,CashFlow_Deferred Income Tax,CashFlow_Depreciation Amortization Depletion,CashFlow_Depreciation And Amortization,CashFlow_Operating Gains Losses,CashFlow_Gain Loss On Investment Securities,CashFlow_Gain Loss On Sale Of Business,CashFlow_Net Income From Continuing Operations,Income_Restructuring And Mergern Acquisition,Balance_Minority Interest,Balance_Other Equity Interest,Balance_Treasury Stock,Balance_Preferred Securities Outside Stock Equity,Balance_Derivative Product Liabilities,Balance_Current Capital Lease Obligation,Balance_Pensionand Other Post Retirement Benefit Plans Current,Balance_Buildings And Improvements,Balance_Cash Financial,CashFlow_Issuance Of Capital Stock,CashFlow_Common Stock Issuance,CashFlow_Change In Prepaid Assets,CashFlow_Unrealized Gain Loss On Investment Securities,CashFlow_Depreciation,Income_Minority Interests,Income_Write Off,Income_Other Operating Expenses,Income_Provision For Doubtful Accounts,Balance_Total Partnership Capital,Balance_Limited Partnership Capital,Balance_Long Term Provisions,Balance_Other Payable,Balance_Non Current Prepaid Assets,Balance_Investment Properties,Balance_Construction In Progress,Balance_Prepaid Assets,Balance_Other Receivables,Balance_Notes Receivable,CashFlow_Short Term Debt Issuance,CashFlow_Net Other Investing Changes,CashFlow_Net Investment Purchase And Sale,CashFlow_Sale Of Investment,CashFlow_Net Intangibles Purchase And Sale,CashFlow_Purchase Of Intangibles,CashFlow_Change In Interest Payable,CashFlow_Earnings Losses From Equity Investments,Income_Gain On Sale Of Ppe,Income_Depreciation Income Statement,Balance_Tradeand Other Payables Non Current,Balance_Dueto Related Parties Current,Balance_Loans Receivable,CashFlow_Cash Dividends Paid,CashFlow_Common Stock Dividend Paid,CashFlow_Sale Of PPE,CashFlow_Change In Other Current Liabilities,CashFlow_Gain Loss On Sale Of PPE,Balance_Preferred Shares Number,Balance_Non Current Deferred Revenue,Balance_Current Deferred Taxes Liabilities,Balance_Interest Payable,Balance_Land And Improvements,Balance_Restricted Cash,Balance_Inventory,Balance_Inventories Adjustments Allowances,Balance_Finished Goods,Balance_Work In Process,Balance_Raw Materials,CashFlow_Change In Inventory,Income_Gain On Sale Of Business,Balance_Liabilities Heldfor Sale Non Current,Balance_Line Of Credit,Balance_Duefrom Related Parties Non Current,Balance_Non Current Accounts Receivable,Balance_Receivables Adjustments Allowances,Balance_Duefrom Related Parties Current,Balance_Other Short Term Investments,CashFlow_Other Cash Adjustment Outside Changein Cash,CashFlow_Cash From Discontinued Financing Activities,CashFlow_Cash From Discontinued Investing Activities,CashFlow_Purchase Of Investment,CashFlow_Sale Of Intangibles,CashFlow_Amortization Cash Flow,CashFlow_Amortization Of Intangibles,CashFlow_Net Foreign Currency Exchange Gain Loss,Balance_Current Provisions,Income_Preferred Stock Dividends,Income_Salaries And Wages,Balance_Preferred Stock Equity,Balance_Dividends Payable,Balance_Investments And Advances,Balance_Long Term Equity Investment,Balance_Current Deferred Assets,Balance_Accrued Interest Receivable,CashFlow_Net Preferred Stock Issuance,CashFlow_Preferred Stock Issuance,Income_Earnings From Equity Interest,Balance_Investmentsin Joint Venturesat Cost,Balance_Investmentsin Associatesat Cost,Balance_Other Investments,CashFlow_Interest Paid Cfo,Balance_Investmentin Financial Assets,Balance_Financial Assets Designatedas Fair Value Through Profitor Loss Total,Balance_Hedging Assets Current,Income_Rent Expense Supplemental,Income_Other Taxes,Income_Amortization,Income_Amortization Of Intangibles Income Statement,Income_Rent And Landing Fees,Balance_Non Current Accrued Expenses,Income_Otherunder Preferred Stock Dividend,Income_Insurance And Claims,Balance_Available For Sale Securities,CashFlow_Interest Received Cfi,CashFlow_Taxes Refund Paid,Balance_Other Inventories,CashFlow_Preferred Stock Payments,Income_Average Dilution Earnings,Balance_Financial Assets,CashFlow_Depletion,CashFlow_Dividends Received Cfi,Income_Earnings From Equity Interest Net Of Tax,Income_Occupancy And Equipment,Income_Professional Expense And Contract Services Expense,Income_Other Non Interest Expense,Balance_Cash Cash Equivalents And Federal Funds Sold,CashFlow_Amortization Of Securities,Balance_Non Current Note Receivables,Balance_Foreign Currency Translation Adjustments,Balance_Cash Equivalents,CashFlow_Interest Paid Cff,Balance_Minimum Pension Liabilities,Balance_Employee Benefits,Balance_Non Current Pension And Other Postretirement Benefit Plans,Balance_Defined Pension Benefit,CashFlow_Cash Flow From Discontinued Operation,CashFlow_Dividend Received Cfo,CashFlow_Pension And Employee Benefit Expense,CashFlow_Preferred Stock Dividend Paid,Balance_Dueto Related Parties Non Current,CashFlow_Interest Received Cfo,Balance_Held To Maturity Securities,Balance_Investments In Other Ventures Under Equity Method,Income_Excise Taxes,CashFlow_Net Investment Properties Purchase And Sale,CashFlow_Sale Of Investment Properties,CashFlow_Purchase Of Investment Properties,Balance_Current Deferred Taxes Assets,Balance_Investmentsin Subsidiariesat Cost,CashFlow_Cash Flowsfromusedin Operating Activities Direct,CashFlow_Interest Paid Direct,CashFlow_Classesof Cash Payments,CashFlow_Paymentsto Suppliersfor Goodsand Services,CashFlow_Classesof Cash Receiptsfrom Operating Activities,CashFlow_Other Cash Receiptsfrom Operating Activities,CashFlow_Receiptsfrom Government Grants,CashFlow_Receiptsfrom Customers,Balance_Unrealized Gain Loss,Balance_Trading Securities,Income_Securities Amortization,CashFlow_Excess Tax Benefit From Stock Based Compensation,CashFlow_Change In Dividend Payable,Balance_Fixed Assets Revaluation Reserve,Income_Loss Adjustment Expense,Income_Net Policyholder Benefits And Claims,Income_Policyholder Benefits Gross,Income_Policyholder Benefits Ceded,Balance_Commercial Paper,Income_Net Income From Tax Loss Carryforward,CashFlow_Other Cash Adjustment Inside Changein Cash,Balance_General Partnership Capital,CashFlow_Dividend Paid Cfo,CashFlow_Taxes Refund Paid Direct,CashFlow_Interest Received Direct,Balance_Restricted Common Stock,Income_Net Income Extraordinary,CashFlow_Other Cash Paymentsfrom Operating Activities,CashFlow_Paymentson Behalfof Employees,Income_Depletion Income Statement,CashFlow_Dividends Received Direct,CashFlow_Dividends Paid Direct,Sector,Industry,Country,Employees,MarketCap,EnterpriseValue,Currency,QuoteType,Website
0,ACCS,ACCESS Newswire Inc. Common Stock,AMEX,-67650.0,0.205,1372000.0,-330000.0,-330000.0,-1558000.0,2993000.0,4999000.0,1042000.0,-1951000.0,-2000.0,2000.0,NaN,-1295650.0,4291000.0,24240000.0,-1871000.0,3859000.0,3858000.0,1.110000,1.110000,4291000.0,4291000.0,4291000.0,4291000.0,5849000.0,-1558000.0,-395000.0,-1953000.0,-330000.0,NaN,-250000.0,NaN,250000.0,-80000.0,-2000.0,NaN,2000.0,NaN,-1621000.0,18935000.0,2687000.0,2687000.0,2692000.0,13556000.0,6405000.0,7151000.0,7151000.0,17314000.0,5305000.0,22619000.0,22619000.0,NaN,3850435.0,3850435.0,NaN,2873000.0,999000.0,32901000.0,-1116000.0,999000.0,317000.0,30345000.0,32031000.0,30345000.0,30345000.0,-96000.0,-96000.0,5432000.0,25005000.0,4000.0,4000.0,0.0,11647000.0,2109000.0,20000.0,86000.0,86000.0,2003000.0,317000.0,1686000.0,9538000.0,NaN,5265000.0,5265000.0,870000.0,870000.0,870000.0,NaN,3403000.0,1769000.0,1634000.0,133000.0,133000.0,1501000.0,41992000.0,33570000.0,73000.0,3691000.0,3691000.0,29346000.0,10303000.0,19043000.0,460000.0,-669000.0,1129000.0,705000.0,324000.0,100000.0,0.0,8422000.0,1513000.0,0.0,3884000.0,NaN,3884000.0,-1336000.0,5220000.0,3025000.0,3025000.0,366000.0,-163000.0,-13391000.0,NaN,-192000.0,413000.0,2208000.0,3025000.0,4103000.0,110000.0,-1188000.0,-13554000.0,-13554000.0,NaN,NaN,-163000.0,-163000.0,-13391000.0,NaN,NaN,-13391000.0,-13391000.0,NaN,11808000.0,11808000.0,12000000.0,12000000.0,NaN,-20000.0,-20000.0,-172000.0,558000.0,NaN,558000.0,-531000.0,208000.0,512000.0,-171000.0,-401000.0,230000.0,154000.0,76000.0,76000.0,-1080000.0,-1080000.0,17000.0,909000.0,1335000.0,250000.0,188000.0,188000.0,2993000.0,2993000.0,-8894000.0,80000.0,-8974000.0,4291000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Communication Services,Advertising Agencies,United States,91.0,24535150.0,24346960.0,USD,EQUITY,https://www.accessnewswire.com
1,AGIG,Abundia Global Impact Group Inc. Common stock,AMEX,0.0,0.000,-13714909.0,-14900411.0,-14900411.0,-29452289.0,220016.0,430118.0,-28615320.0,-28835336.0,-3942229.0,625599.0,25370.0,-14551878.0,-29452289.0,11028927.0,-28747387.0,32847237.0,32847237.0,-0.900000,-0.900000,-29452289.0,-29452289.0,-29452289.0,-29460935.0,NaN,-29460935.0,0.0,-29460935.0,-14900411.0,NaN,-14929660.0,13270632.0,544028.0,29249.0,-3942229.0,3342000.0,625599.0,25370.0,-10618295.0,10598809.0,NaN,NaN,752287.0,10584333.0,NaN,10584333.0,10584333.0,-19486.0,430118.0,410632.0,410632.0,NaN,36918281.0,36918281.0,5610215.0,10389975.0,4629972.0,29243253.0,-1043785.0,4629972.0,161139.0,19014417.0,25274691.0,19014417.0,19014417.0,-5314.0,-5314.0,-46055127.0,65037940.0,36918.0,36918.0,NaN,12841012.0,6439464.0,NaN,NaN,NaN,6407216.0,146942.0,6260274.0,6401548.0,NaN,NaN,NaN,3982759.0,3968562.0,NaN,3968562.0,2418789.0,NaN,2418789.0,NaN,NaN,2175672.0,31855429.0,26497666.0,12286.0,NaN,NaN,14384445.0,1398295.0,12986150.0,8733660.0,-627816.0,9361476.0,NaN,8730646.0,NaN,NaN,5357763.0,179209.0,NaN,56925.0,NaN,56925.0,NaN,NaN,4618621.0,4618621.0,-18098917.0,NaN,-6444139.0,13310972.0,-10046859.0,NaN,NaN,4618621.0,525809.0,63613.0,4029199.0,15177110.0,15177110.0,NaN,NaN,8310277.0,NaN,6866833.0,3935000.0,-450000.0,2931833.0,-5994139.0,8925972.0,-3095853.0,-3095853.0,NaN,NaN,NaN,-8660829.0,-8660829.0,NaN,-8052058.0,NaN,-8052058.0,1326843.0,NaN,86805.0,1070681.0,433561.0,637120.0,421359.0,NaN,NaN,181405.0,-24019.0,15846013.0,NaN,0.0,1659028.0,NaN,NaN,220016.0,209065.0,2356977.0,-45965.0,NaN,-29460935.0,NaN,0.0,NaN,NaN,NaN,NaN,14197.0,NaN,NaN,NaN,8310277.0,8310277.0,-12048.0,NaN,NaN,8646.0,1115000.0,-737811.0,0.0,NaN,NaN,32248.0,243117.0,2005025.0,1362250.0,630830.0,503008.0,NaN,NaN,4385000.0,NaN,6951006.0,6951006.0,-1386030.0,-1386030.0,433561.0,1522563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Utilities,Utilities - Renewable,United States,2.0,51506696.0,40063780.0,USD,EQUITY,https://abundiaimpact.com
2,AIB,"BlockchAIn Digital Infrastructure, Inc Common ...",AMEX,0.0,0.000,-103195.0,67714.0,67714.0,-835431.0,862305.0,15001351.0,-35481.0,-897786.0,NaN,NaN,NaN,-903145.0,-835431.0,19414398.0,-897786.0,37646133.0,37646133.0,-0.022192,-0.022192,-835431.0,-835431.0,-835431.0,-835431.0,NaN,-835431.0,NaN,-835431.0,62355.0,-5359.0,67714.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-897786.0,4413047.0,862305.0,862305.0,NaN,3550742.0,NaN,NaN,NaN,3515261.0,15001351.0,18516612.0,18516612.0,NaN,37646133.0,37646133.0,NaN,81712.0,3008145.0,7859281.0,-5258420.0,3008145.0,81712.0,7859281.0,7859281.0,7859281.0,7859281.0,NaN,NaN,7859281.0,0.0,0.0,0.0,0.0,9408235.0,680166.0,NaN,NaN,NaN,0.0,0.0,NaN,8728069.0,1845760.0,2330584.0,2330584.0,81712.0,NaN,NaN,NaN,4470013.0,NaN,4470013.0,NaN,NaN,3304012.0,17267516.0,13797867.0,NaN,NaN,NaN,4851136.0,NaN,4851136.0,8946731.0,-1495908.0,10442639.0,2846345.0,7423705.0,172589.0,0.0,3469649.0,218698.0,0.0,3235686.0,NaN,2152226.0,NaN,NaN,15265.0,15265.0,2297032.0,NaN,NaN,NaN,-38927.0,NaN,NaN,15265.0,131107.0,NaN,-115842.0,-2506729.0,-2506729.0,-485833.0,NaN,3889834.0,NaN,-18750.0,-18750.0,NaN,NaN,NaN,NaN,54928.0,54928.0,NaN,NaN,NaN,93073.0,-38927.0,NaN,2335959.0,NaN,2335959.0,2376799.0,664004.0,-158627.0,1448123.0,NaN,NaN,NaN,NaN,NaN,-1422460.0,-1422460.0,NaN,NaN,NaN,NaN,NaN,NaN,862305.0,862305.0,-67714.0,NaN,NaN,-835431.0,NaN,NaN,NaN,NaN,NaN,NaN,81712.0,NaN,NaN,15265.0,3889834.0,3889834.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1166001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38145.0,NaN,NaN,NaN,NaN,NaN,NaN,67714.0,NaN,680166.0,NaN,1083460.0,-5891980.0,-5891980.0,132000.0,1845759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,Software - Application,United States,3.0,135902528.0,113278776.0,USD,EQUITY,https://www.oneblockchain.ai

### **2.2 Dataset description**

In [5]:
financials_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4576 entries, 0 to 4575
Columns: 360 entries, Symbol to Website
dtypes: float64(351), str(9)
memory usage: 12.6 MB

In [6]:
financials_df.describe().T.head(20)

,count,mean,std,min,25%,50%,75%,max
Income_Tax Effect Of Unusual Items,4573.0,-3.105859e+08,1.463905e+10,-7.838690e+11,-1.765680e+06,0.000000e+00,0.000000e+00,2.348990e+11
Income_Tax Rate For Calcs,4569.0,1.716604e-01,1.038284e-01,0.000000e+00,9.300000e-02,2.100000e-01,2.330000e-01,4.000000e-01
Income_Normalized EBITDA,4048.0,3.270788e+10,1.788561e+12,-6.651988e+13,-5.521470e+06,6.408400e+07,6.144380e+08,7.343200e+13
Income_Total Unusual Items,3626.0,-2.167490e+09,8.837795e+10,-3.919345e+12,-2.876875e+07,-1.314000e+06,1.049750e+06,8.945870e+11
Income_Total Unusual Items Excluding Goodwill,3627.0,-2.167066e+09,8.836577e+10,-3.919345e+12,-2.878950e+07,-1.316000e+06,1.049500e+06,8.945870e+11
Income_Net Income From Continuing Operation Net Minority Interest,4572.0,-5.395741e+09,1.513552e+12,-9.938466e+13,-2.243575e+07,1.190650e+07,2.339192e+08,1.748600e+13
Income_Reconciled Depreciation,4472.0,2.465760e+10,6.815284e+11,-1.829000e+09,3.149193e+06,2.731600e+07,1.759378e+08,3.765300e+13
Income_Reconciled Cost Of Revenue,3860.0,1.265812e+11,2.982689e+12,-1.370920e+08,3.500772e+07,3.285620e+08,2.000906e+09,1.310891e+14
Income_EBITDA,4045.0,3.169482e+10,1.825854e+12,-7.043922e+13,-9.077760e+06,4.704764e+07,5.660210e+08,7.337000e+13
Income_EBIT,4136.0,5.696077e+09,1.486022e+12,-8.189647e+13,-1.823878e+07,1.691550e+07,3.813865e+08,3.571700e+13
Income_Net Interest Income,4401.0,4.016900e+09,4.868064e+11,-2.172855e+13,-5.574700e+07,-2.669000e+06,1.966803e+06,1.307309e+13
Income_Interest Expense,3806.0,3.137128e+10,5.700242e+11,-2.970000e+05,2.614099e+06,2.853950e+07,1.504702e+08,1.732909e+13
Income_Interest Income,2922.0,4.859163e+10,9.113196e+11,-3.339000e+09,1.361000e+06,1.000000e+07,6.951150e+07,2.915610e+13
Income_Normalized Income,4568.0,-3.990895e+09,1.469853e+12,-9.624918e+13,-1.603357e+07,1.447300e+07,2.450433e+08,1.753471e+13
Income_Net Income From Continuing And Discontinued Operation,4571.0,-5.392130e+09,1.513717e+12,-9.938466e+13,-2.270900e+07,1.229365e+07,2.384135e+08,1.748600e+13
Income_Total Expenses,4148.0,1.686532e+11,3.904626e+12,-1.660360e+09,9.339285e+07,6.080525e+08,3.102050e+09,1.636502e+14
Income_Total Operating Income As Reported,3616.0,5.047872e+09,1.448896e+12,-7.409420e+13,-2.310550e+07,4.960500e+06,2.585252e+08,3.405700e+13
Income_Diluted Average Shares,3769.0,2.700376e+08,9.941030e+08,2.527000e+03,2.135965e+07,6.155800e+07,1.792900e+08,2.451400e+10
Income_Basic Average Shares,3761.0,2.664013e+08,9.871179e+08,2.527000e+03,2.118300e+07,6.050000e+07,1.744370e+08,2.435900e+10
Income_Diluted EPS,3764.0,1.248657e+02,9.196834e+03,-9.296435e+04,-6.800000e-01,6.400000e-01,3.272500e+00,5.542325e+05

# **3. Data Preprocessing**

### **3.1 Missing Value Analysis**

Here we group the columns depending on type to process easily

In [14]:
identifier_columns = [
    "Symbol",
    "Company Name",
    "Exchange",
]

metadata_columns = [
    "Sector",
    "Industry",
    "Country",
    "Employees",
    "MarketCap",
    "EnterpriseValue",
    "Currency",
    "QuoteType",
    "Website",
]

financial_columns = [
    col for col in financials_df.columns
    if col.startswith("Income_")
    or col.startswith("Balance_")
    or col.startswith("CashFlow_")
]

print(f"Identifier columns: {len(identifier_columns)}")
print(f"Metadata columns: {len(metadata_columns)}")
print(f"Financial columns: {len(financial_columns)}")

Identifier columns: 3
Metadata columns: 9
Financial columns: 348

In [15]:
missing_summary = (
    financials_df.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .reset_index()
)

missing_summary.columns = ["Column", "Missing %"]

missing_summary.head(30)

                                               Column   Missing %
0                      CashFlow_Dividends Paid Direct  100.000000
1                     Balance_Restricted Common Stock   99.978147
2             CashFlow_Receiptsfrom Government Grants   99.956294
3                  CashFlow_Dividends Received Direct   99.934441
4                   Income_Depletion Income Statement   99.912587
5              CashFlow_Paymentson Behalfof Employees   99.890734
6                 CashFlow_Change In Dividend Payable   99.868881
7                 Balance_General Partnership Capital   99.847028
8        Income_Net Income From Tax Loss Carryforward   99.825175
9                          CashFlow_Dividend Paid Cfo   99.825175
10  CashFlow_Other Cash Receiptsfrom Operating Act...   99.803322
11  CashFlow_Other Cash Paymentsfrom Operating Act...   99.803322
12                  CashFlow_Interest Received Direct   99.803322
13                      CashFlow_Interest Paid Direct   99.781469
14                    Income_Net Income Extraordinary   99.781469
15                  CashFlow_Taxes Refund Paid Direct   99.737762
16  CashFlow_Paymentsto Suppliersfor Goodsand Serv...   99.715909
17              Balance_Current Deferred Taxes Assets   99.715909
18  CashFlow_Other Cash Adjustment Inside Changein...   99.694056
19                    CashFlow_Receiptsfrom Customers   99.694056
20                     Income_Securities Amortization   99.650350
21  CashFlow_Classesof Cash Receiptsfrom Operating...   99.650350
22           Balance_Fixed Assets Revaluation Reserve   99.650350
23  CashFlow_Cash Flowsfromusedin Operating Activi...   99.628497
24                   CashFlow_Classesof Cash Payments   99.628497
25                Balance_Limited Partnership Capital   99.497378
26          Balance_Investmentsin Subsidiariesat Cost   99.497378
27                  Balance_Total Partnership Capital   99.431818
28         Balance_Current Deferred Taxes Liabilities   99.300699
29  CashFlow_Excess Tax Benefit From Stock Based C...   99.278846

A lof of missing values for more obscure financial metrics; this is expected

In [16]:
financial_coverage = (
    financials_df[financial_columns]
    .notna()
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

financial_coverage.columns = ["Financial Feature", "Non-Missing Count"]

financial_coverage["Coverage %"] = (
    financial_coverage["Non-Missing Count"] / len(financials_df) * 100
)

financial_coverage.head(30)

,Financial Feature,Non-Missing Count,Coverage %
0,Income_Total Revenue,4576,100.000000
1,Income_Tax Effect Of Unusual Items,4573,99.934441
2,Income_Net Income From Continuing Operation Ne...,4572,99.912587
3,Income_Diluted NI Availto Com Stockholders,4572,99.912587
4,Income_Net Income Common Stockholders,4572,99.912587
5,Balance_Total Assets,4571,99.890734
6,Income_Net Income Including Noncontrolling Int...,4571,99.890734
7,Income_Net Income From Continuing And Disconti...,4571,99.890734
8,Balance_Common Stock Equity,4570,99.868881
9,Balance_Total Liabilities Net Minority Interest,4569,99.847028
10,Balance_Total Equity Gross Minority Interest,4569,99.847028
11,Income_Net Income,4569,99.847028
12,Income_Tax Rate For Calcs,4569,99.847028
13,Balance_Net Tangible Assets,4568,99.825175
14,Income_Normalized Income,4568,99.825175
15,Income_Operating Revenue,4568,99.825175
16,Income_Pretax Income,4568,99.825175
17,Income_Net Income Continuous Operations,4566,99.781469
18,Balance_Tangible Book Value,4566,99.781469
19,Balance_Stockholders Equity,4565,99.759615
20,CashFlow_Free Cash Flow,4565,99.759615
21,CashFlow_Beginning Cash Position,4565,99.759615
22,Balance_Cash And Cash Equivalents,4565,99.759615
23,Balance_Ordinary Shares Number,4563,99.715909
24,Balance_Share Issued,4563,99.715909
25,CashFlow_End Cash Position,4561,99.672203
26,CashFlow_Financing Cash Flow,4558,99.606643
27,CashFlow_Changes In Cash,4556,99.562937
28,CashFlow_Net Income From Continuing Operations,4545,99.322552
29,CashFlow_Operating Cash Flow,4545,99.322552

### **3.2 Remove Sparse Financial Features**

In [17]:
MAX_MISSING_PCT = 80 # We can tweak this threshold as needed

financial_missing_pct = financials_df[financial_columns].isna().mean() * 100

financial_columns_to_keep = financial_missing_pct[
    financial_missing_pct <= MAX_MISSING_PCT
].index.tolist()

financial_columns_to_drop = financial_missing_pct[
    financial_missing_pct > MAX_MISSING_PCT
].index.tolist()

print(f"Financial columns before filtering: {len(financial_columns):,}")
print(f"Financial columns kept: {len(financial_columns_to_keep):,}")
print(f"Financial columns dropped: {len(financial_columns_to_drop):,}")

Financial columns before filtering: 348
Financial columns kept: 214
Financial columns dropped: 134

### **3.3 Sector and Coverage**

In [18]:
sector_counts = financials_df["Sector"].value_counts(dropna=False)
sector_counts

Sector
Technology                751
Healthcare                740
Financial Services        707
Industrials               660
Consumer Cyclical         527
Communication Services    253
Consumer Defensive        230
Basic Materials           219
Energy                    206
Real Estate               175
Utilities                  98
NaN                        10
Name: count, dtype: int64

In [19]:
industry_counts = financials_df["Industry"].value_counts(dropna=False)
industry_counts.head(30)

Industry
Biotechnology                               302
Banks - Regional                            296
Software - Application                      215
Software - Infrastructure                   163
Medical Devices                             129
Asset Management                            109
Capital Markets                              87
Aerospace & Defense                          77
Drug Manufacturers - Specialty & Generic     76
Specialty Industrial Machinery               73
Internet Content & Information               69
Information Technology Services              68
Semiconductors                               66
Packaged Foods                               63
Oil & Gas E&P                                62
Auto Parts                                   56
Specialty Chemicals                          55
Telecom Services                             54
Engineering & Construction                   53
Restaurants                                  52
Medical Instruments & Supplies               51
Medical Care Facilities                      49
Credit Services                              49
Entertainment                                49
Electronic Components                        48
Specialty Retail                             47
Oil & Gas Equipment & Services               47
Insurance - Property & Casualty              45
Diagnostics & Research                       45
Electrical Equipment & Parts                 44
Name: count, dtype: int64

### **3.4 Remove Constant Columns**

In [20]:
candidate_columns = metadata_columns + financial_columns_to_keep

available_candidate_columns = [
    col for col in candidate_columns
    if col in financials_df.columns
]

nunique_summary = (
    financials_df[available_candidate_columns]
    .nunique(dropna=False)
    .sort_values()
    .reset_index()
)

nunique_summary.columns = ["Column", "Unique Values"]

nunique_summary.head(30)

                                              Column  Unique Values
0                                           Currency              1
1                                          QuoteType              1
2                                             Sector             12
3                                            Country             58
4                                           Industry            146
5                                 Balance_Properties            222
6                            Balance_Preferred Stock            383
7                          CashFlow_Sale Of Business            678
8                   CashFlow_Purchase Of Intangibles            763
9         CashFlow_Net Intangibles Purchase And Sale            816
10  CashFlow_Earnings Losses From Equity Investments            857
11                    CashFlow_Change In Tax Payable            861
12             CashFlow_Change In Income Tax Payable            861
13                          Balance_Interest Payable            863
14               Income_Impairment Of Capital Assets            880
15              Balance_Non Current Deferred Revenue            881
16               Balance_Long Term Equity Investment           1002
17                      Income_Other Special Charges           1007
18             CashFlow_Net Short Term Debt Issuance           1020
19                              CashFlow_Sale Of PPE           1021
20      Income_Restructuring And Mergern Acquisition           1037
21                 CashFlow_Gain Loss On Sale Of PPE           1057
22                           Balance_Restricted Cash           1067
23             CashFlow_Capital Expenditure Reported           1087
24                           Balance_Work In Process           1106
25                          Balance_Taxes Receivable           1112
26                         Income_Salaries And Wages           1161
27                             Balance_Other Payable           1184
28                            Balance_Cash Financial           1186
29                        Balance_Income Tax Payable           1258

All values are in USD, so no currency conversion is needed

In [21]:
constant_columns = nunique_summary[
    nunique_summary["Unique Values"] <= 1
]["Column"].tolist()

print(f"Constant columns to drop: {len(constant_columns)}")
constant_columns

Constant columns to drop: 2

['Currency', 'QuoteType']

Luckily, only 2 columns were dropped here

In [22]:
metadata_columns_to_keep = [
    "Sector",
    "Industry",
    "Employees",
    "MarketCap",
    "EnterpriseValue",
    "Currency",
]

base_columns_to_keep = [
    col for col in identifier_columns + metadata_columns_to_keep
    if col in financials_df.columns
]

columns_to_keep = base_columns_to_keep + financial_columns_to_keep

clean_financials_df = financials_df[columns_to_keep].copy()

clean_financials_df = clean_financials_df.drop(
    columns=[col for col in constant_columns if col in clean_financials_df.columns]
)

print(f"Original dataset shape: {financials_df.shape}")
print(f"Cleaned dataset shape: {clean_financials_df.shape}")

clean_financials_df.head()

Original dataset shape: (4576, 360)
Cleaned dataset shape: (4576, 222)

,Symbol,Company Name,Exchange,Sector,Industry,Employees,MarketCap,EnterpriseValue,Income_Tax Effect Of Unusual Items,Income_Tax Rate For Calcs,Income_Normalized EBITDA,Income_Total Unusual Items,Income_Total Unusual Items Excluding Goodwill,Income_Net Income From Continuing Operation Net Minority Interest,Income_Reconciled Depreciation,Income_Reconciled Cost Of Revenue,Income_EBITDA,Income_EBIT,Income_Net Interest Income,Income_Interest Expense,Income_Interest Income,Income_Normalized Income,Income_Net Income From Continuing And Discontinued Operation,Income_Total Expenses,Income_Total Operating Income As Reported,Income_Diluted Average Shares,Income_Basic Average Shares,Income_Diluted EPS,Income_Basic EPS,Income_Diluted NI Availto Com Stockholders,Income_Net Income Common Stockholders,Income_Net Income,Income_Net Income Including Noncontrolling Interests,Income_Net Income Continuous Operations,Income_Tax Provision,Income_Pretax Income,Income_Other Income Expense,Income_Other Non Operating Income Expenses,Income_Special Income Charges,Income_Other Special Charges,Income_Impairment Of Capital Assets,Income_Gain On Sale Of Security,Income_Net Non Operating Interest Income Expense,Income_Interest Expense Non Operating,Income_Interest Income Non Operating,Income_Operating Income,Income_Operating Expense,Income_Depreciation Amortization Depletion Income Statement,Income_Depreciation And Amortization In Income Statement,Income_Research And Development,Income_Selling General And Administration,Income_Selling And Marketing Expense,Income_General And Administrative Expense,Income_Other Gand A,Income_Gross Profit,Income_Cost Of Revenue,Income_Total Revenue,Income_Operating Revenue,Balance_Treasury Shares Number,Balance_Ordinary Shares Number,Balance_Share Issued,Balance_Net Debt,Balance_Total Debt,Balance_Tangible Book Value,Balance_Invested Capital,Balance_Working Capital,Balance_Net Tangible Assets,Balance_Capital Lease Obligations,Balance_Common Stock Equity,Balance_Total Capitalization,Balance_Total Equity Gross Minority Interest,Balance_Stockholders Equity,Balance_Gains Losses Not Affecting Retained Earnings,Balance_Other Equity Adjustments,Balance_Retained Earnings,Balance_Additional Paid In Capital,Balance_Capital Stock,Balance_Common Stock,Balance_Preferred Stock,Balance_Total Liabilities Net Minority Interest,Balance_Total Non Current Liabilities Net Minority Interest,Balance_Other Non Current Liabilities,Balance_Non Current Deferred Liabilities,Balance_Non Current Deferred Taxes Liabilities,Balance_Long Term Debt And Capital Lease Obligation,Balance_Long Term Capital Lease Obligation,Balance_Long Term Debt,Balance_Current Liabilities,Balance_Other Current Liabilities,Balance_Current Deferred Liabilities,Balance_Current Deferred Revenue,Balance_Current Debt And Capital Lease Obligation,Balance_Current Debt,Balance_Other Current Borrowings,Balance_Payables And Accrued Expenses,Balance_Current Accrued Expenses,Balance_Payables,Balance_Total Tax Payable,Balance_Income Tax Payable,Balance_Accounts Payable,Balance_Total Assets,Balance_Total Non Current Assets,Balance_Other Non Current Assets,Balance_Non Current Deferred Assets,Balance_Non Current Deferred Taxes Assets,Balance_Goodwill And Other Intangible Assets,Balance_Other Intangible Assets,Balance_Goodwill,Balance_Net PPE,Balance_Accumulated Depreciation,Balance_Gross PPE,Balance_Leases,Balance_Other Properties,Balance_Machinery Furniture Equipment,Balance_Properties,Balance_Current Assets,Balance_Other Current Assets,Balance_Receivables,Balance_Taxes Receivable,Balance_Accounts Receivable,Balance_Allowance For Doubtful Accounts Receivable,Balance_Gross Accounts Receivable,Balance_Cash Cash Equivalents And Short Term Investments,Balance_Cash And Cash Equivalents,CashFlow_Free Cash Flow,CashFlow_Repurchase Of Capital Stock,CashFlow_Repayment Of Debt,CashFlow_Issuance Of Debt,CashFlow_Capital Expenditure,CashFlow_Interest Paid Supplemental Data,CashFlow_Income Tax Paid Supplemental Data,CashFlow_End Cash Position,CashFlow_Beginning Cash Position,CashFlow_Effect Of Exchange Rate Changes,CashFlow_Changes In Cash,CashFlow_Financing Cash Flow,CashFlow_Cash Flow From Continuing Financing Activities,CashFlow_Net Other Financing Charges,CashFlow_Proceeds From Stock Option Exercised,CashFlow_Net Common Stock Issuance,CashFlow_Common Stock Payments,CashFlow_Net Issuance Payments Of Debt,CashFlow_Net Short Term Debt Issuance,CashFlow_Net Long Term Debt Issuance,CashFlow_Long Term Debt Payments,CashFlow_Long Term Debt Issuance,CashFlow_Investing Cash Flow,CashFlow_Cash Flow From Continuing Investing Activities,CashFlow_Net Business Purchase And Sale,CashFlow_Sale Of Business,CashFlow_Purchase Of Business,CashFlow_Net PPE Purchase And Sale,CashFlow_Purchase Of PPE,CashFlow_Capital Expenditure Reported,CashFlow_Operating Cash Flow,CashFlow_Cash Flow From Continuing Operating Activities,CashFlow_Change In Working Capital,CashFlow_Change In Other Working Capital,CashFlow_Change In Other Current Assets,CashFlow_Change In Payables And Accrued Expense,CashFlow_Change In Accrued Expense,CashFlow_Change In Payable,CashFlow_Change In Account Payable,CashFlow_Change In Tax Payable,CashFlow_Change In Income Tax Payable,CashFlow_Change In Receivables,CashFlow_Changes In Account Receivables,CashFlow_Other Non Cash Items,CashFlow_Stock Based Compensation,CashFlow_Provisionand Write Offof Assets,CashFlow_Asset Impairment Charge,CashFlow_Deferred Tax,CashFlow_Deferred Income Tax,CashFlow_Depreciation Amortization Depletion,CashFlow_Depreciation And Amortization,CashFlow_Operating Gains Losses,CashFlow_Gain Loss On Investment Securities,CashFlow_Net Income From Continuing Operations,Income_Restructuring And Mergern Acquisition,Balance_Minority Interest,Balance_Treasury Stock,Balance_Current Capital Lease Obligation,Balance_Pensionand Other Post Retirement Benefit Plans Current,Balance_Buildings And Improvements,Balance_Cash Financial,CashFlow_Issuance Of Capital Stock,CashFlow_Common Stock Issuance,CashFlow_Change In Prepaid Assets,CashFlow_Depreciation,Income_Minority Interests,Income_Other Operating Expenses,Balance_Other Payable,Balance_Construction In Progress,Balance_Prepaid Assets,Balance_Other Receivables,CashFlow_Net Other Investing Changes,CashFlow_Net Investment Purchase And Sale,CashFlow_Sale Of Investment,CashFlow_Net Intangibles Purchase And Sale,CashFlow_Purchase Of Intangibles,CashFlow_Earnings Losses From Equity Investments,CashFlow_Cash Dividends Paid,CashFlow_Common Stock Dividend Paid,CashFlow_Sale Of PPE,CashFlow_Change In Other Current Liabilities,CashFlow_Gain Loss On Sale Of PPE,Balance_Non Current Deferred Revenue,Balance_Interest Payable,Balance_Land And Improvements,Balance_Restricted Cash,Balance_Inventory,Balance_Finished Goods,Balance_Work In Process,Balance_Raw Materials,CashFlow_Change In Inventory,Balance_Other Short Term Investments,CashFlow_Purchase Of Investment,CashFlow_Amortization Cash Flow,CashFlow_Amortization Of Intangibles,Income_Salaries And Wages,Balance_Investments And Advances,Balance_Long Term Equity Investment
0,ACCS,ACCESS Newswire Inc. Common Stock,AMEX,Communication Services,Advertising Agencies,91.0,24535150.0,24346960.0,-67650.0,0.205,1372000.0,-330000.0,-330000.0,-1558000.0,2993000.0,4999000.0,1042000.0,-1951000.0,-2000.0,2000.0,NaN,-1295650.0,4291000.0,24240000.0,-1871000.0,3859000.0,3858000.0,1.110000,1.110000,4291000.0,4291000.0,4291000.0,4291000.0,-1558000.0,-395000.0,-1953000.0,-330000.0,NaN,-250000.0,NaN,250000.0,-80000.0,-2000.0,2000.0,NaN,-1621000.0,18935000.0,2687000.0,2687000.0,2692000.0,13556000.0,6405000.0,7151000.0,7151000.0,17314000.0,5305000.0,22619000.0,22619000.0,NaN,3850435.0,3850435.0,NaN,2873000.0,999000.0,32901000.0,-1116000.0,999000.0,317000.0,30345000.0,32031000.0,30345000.0,30345000.0,-96000.0,-96000.0,5432000.0,25005000.0,4000.0,4000.0,0.0,11647000.0,2109000.0,20000.0,86000.0,86000.0,2003000.0,317000.0,1686000.0,9538000.0,NaN,5265000.0,5265000.0,870000.0,870000.0,870000.0,3403000.0,1769000.0,1634000.0,133000.0,133000.0,1501000.0,41992000.0,33570000.0,73000.0,3691000.0,3691000.0,29346000.0,10303000.0,19043000.0,460000.0,-669000.0,1129000.0,705000.0,324000.0,100000.0,0.0,8422000.0,1513000.0,3884000.0,NaN,3884000.0,-1336000.0,5220000.0,3025000.0,3025000.0,366000.0,-163000.0,-13391000.0,NaN,-192000.0,413000.0,2208000.0,3025000.0,4103000.0,110000.0,-1188000.0,-13554000.0,-13554000.0,NaN,NaN,-163000.0,-163000.0,-13391000.0,NaN,-13391000.0,-13391000.0,NaN,11808000.0,11808000.0,12000000.0,12000000.0,NaN,-20000.0,-20000.0,-172000.0,558000.0,558000.0,-531000.0,208000.0,512000.0,-171000.0,-401000.0,230000.0,154000.0,76000.0,76000.0,-1080000.0,-1080000.0,17000.0,909000.0,1335000.0,250000.0,188000.0,188000.0,2993000.0,2993000.0,-8894000.0,80000.0,4291000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGIG,Abundia Global Impact Group Inc. Common stock,AMEX,Utilities,Utilities - Renewable,2.0,51506696.0,40063780.0,0.0,0.000,-13714909.0,-14900411.0,-14900411.0,-29452289.0,220016.0,430118.0,-28615320.0,-28835336.0,-3942229.0,625599.0,25370.0,-14551878.0,-29452289.0,11028927.0,-28747387.0,32847237.0,32847237.0,-0.900000,-0.900000,-29452289.0,-29452289.0,-29452289.0,-29460935.0,-29460935.0,0.0,-29460935.0,-14900411.0,NaN,-14929660.0,13270632.0,544028.0,29249.0,-3942229.0,625599.0,25370.0,-10618295.0,10598809.0,NaN,NaN,752287.0,10584333.0,NaN,10584333.0,10584333.0,-19486.0,430118.0,410632.0,410632.0,NaN,36918281.0,36918281.0,5610215.0,10389975.0,4629972.0,29243253.0,-1043785.0,4629972.0,161139.0,19014417.0,25274691.0,19014417.0,19014417.0,-5314.0,-5314.0,-46055127.0,65037940.0,36918.0,36918.0,NaN,12841012.0,6439464.0,NaN,NaN,NaN,6407216.0,146942.0,6260274.0,6401548.0,NaN,NaN,NaN,3982759.0,3968562.0,NaN,2418789.0,NaN,2418789.0,NaN,NaN,2175672.0,31855429.0,26497666.0,12286.0,NaN,NaN,14384445.0,1398295.0,12986150.0,8733660.0,-627816.0,9361476.0,NaN,8730646.0,NaN,NaN,5357763.0,179209.0,56925.0,NaN,56925.0,NaN,NaN,4618621.0,4618621.0,-18098917.0,NaN,-6444139.0,13310972.0,-10046859.0,NaN,NaN,4618621.0,525809.0,63613.0,4029199.0,15177110.0,15177110.0,NaN,NaN,8310277.0,NaN,6866833.0,3935000.0,2931833.0,-5994139.0,8925972.0,-3095853.0,-3095853.0,NaN,NaN,NaN,-8660829.0,-8660829.0,NaN,-8052058.0,-8052058.0,1326843.0,NaN,86805.0,1070681.0,433561.0,637120.0,421359.0,NaN,NaN,181405.0,-24019.0,15846013.0,NaN,0.0,1659028.0,NaN,NaN,220016.0,209065.0,2356977.0,-45965.0,-29460935.0,NaN,0.0,NaN,14197.0,NaN,NaN,NaN,8310277.0,8310277.0,-12048.0,NaN,8646.0,-737811.0,243117.0,630830.0,503008.0,NaN,NaN,6951006.0,6951006.0,-1386030.0,-1386030.0,1522563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AIB,"BlockchAIn Digital Infrastructure, Inc Common ...",AMEX,Technology,Software - Application,3.0,135902528.0,113278776.0,0.0,0.000,-103195.0,67714.0,67714.0,-835431.0,862305.0,15001351.0,-35481.0,-897786.0,NaN,NaN,NaN,-903145.0,-835431.0,19414398.0,-897786.0,37646133.0,37646133.0,-0.022192,-0.022192,-835431.0,-835431.0,-835431.0,-835431.0,-835431.0,NaN,-835431.0,62355.0,-5359.0,67714.0,NaN,NaN,NaN,NaN,NaN,NaN,-897786.0,4413047.0,862305.0,862305.0,NaN,3550742.0,NaN,NaN,NaN,3515261.0,15001351.0,18516612.0,18516612.0,NaN,37646133.0,37646133.0,NaN,81712.0,3008145.0,7859281.0,-5258420.0,3008145.0,81712.0,7859281.0,7859281.0,7859281.0,7859281.0,NaN,NaN,7859281.0,0.0,0.0,0.0,0.0,9408235.0,680166.0,NaN,NaN,NaN,0.0,0.0,NaN,8728069.0,1845760.0,2330584.0,2330584.0,81712.0,NaN,NaN,4470013.0,NaN,4470013.0,NaN,NaN,3304012.0,17267516.0,13797867.0,NaN,NaN,NaN,4851136.0,NaN,4851136.0,8946731.0,-1495908.0,10442639.0,2846345.0,7423705.0,172589.0,0.0,3469649.0,218698.0,3235686.0,NaN,2152226.0,NaN,NaN,15265.0,15265.0,2297032.0,NaN,NaN,NaN,-38927.0,NaN,NaN,15265.0,131107.0,NaN,-115842.0,-2506729.0,-2506729.0,-485833.0,NaN,3889834.0,NaN,-18750.0,-18750.0,NaN,NaN,NaN,54928.0,54928.0,NaN,NaN,NaN,93073.0,-38927.0,NaN,2335959.0,2335959.0,2376799.0,664004.0,-158627.0,1448123.0,NaN,NaN,NaN,NaN,NaN,-1422460.0,-1422460.0,NaN,NaN,NaN,NaN,NaN,NaN,862305.0,862305.0,-67714.0,NaN,-835431.0,NaN,NaN,NaN,81712.0,NaN,NaN,15265.0,3889834.0,3889834.0,NaN,NaN,NaN,NaN,1166001.0,NaN,NaN,NaN,-38145.0,NaN,NaN,NaN,NaN,NaN,-5891980.0,-5891980.0,132000.0,1845759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AIRI,Air Industries Group Common Stock,AMEX,Industrials,Aerospace & Defense,160.0,14746000.0,46463012.0,0.0,0.091,3777000.0,NaN,NaN,-1305000.0,3372000.0,39734000.0,3777000.0,405000.0,-1841000.0,1841000.0,NaN,-1305000.0,-1305000.0,48259000.0,-338000.0,4216918.0,4216918.0,-0.310000,-0.310000,-1305000.0,-1305000.0,-1305000.0,-1305000.0,-1305000.0,-131000.0,-1436000.0,743000.0,743000.0,NaN,NaN,NaN,NaN,-1841000.0,1841000.0,NaN,-338000.0,8525000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8187000.0,39734000.0,47921000.0,47921000.0,NaN,4776454.0,4776454.0,29424000.0,30806000.0,19201000.0,49305000.0,9168000.0,19201000.0,702000.0,19201000.0,20713000.0,19201000.0,19201000.0,NaN,NaN,-70412000.0,89608000.0,5000.0,5000.0,0.0,39128000.0,1512000.0,NaN,0.0,NaN,1512000.0,0.0,1512000.0,37616000.0,NaN,419000.0,419000.0,29294000.0,28592000.0,28592000.0,7903000.0,803000.0,7100000.0,NaN,NaN,7100000.0,58329000.0,11545000.0,614000.0,NaN,NaN,NaN,NaN,NaN,10931000.0,-39201000.0,50132000.0,1139000.0,17708000.0,28233000.0,0.0,46784000.0,766000.0,7071000.0,NaN,7071000.0,-464000.0,7535000.0,680000.0,680000.0,-4674000.0,NaN,-2533000.0,6353000.0,-3322000.0,1829000.0,21000.0,4610000.0,753000.0,NaN,3857000.0,8331000.0,8331000.0,-127000.0,NaN,4638000.0,NaN,3820000.0,5343000.0,-1523000.0,-1523000.0,0.0,-3122000.0,-3122000.0,NaN,NaN,NaN,-3122000.0,-3322000.0,NaN,-1352000.0,-1352000.0,-4496000.0,-724000.0,NaN,888000.0,NaN,NaN,NaN,NaN,NaN,2057000.0,1761000.0,69000.0,1047000.0,68000.0,NaN,NaN,NaN,3372000.0,3372000.0,-107000.0,-39000.0,-1305000.0,NaN,NaN,NaN,702000.0,0.0,2739000.0,680000.0,4638000.0,4638000.0,-386000.0,3372000.0,NaN,8525000.0,NaN,NaN,76000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.0,-881000.0,-68000.0,0.0,NaN,313000.0,3930000.0,34261000.0,677000.0,26278000.0,7306000.0,-5450000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AMBO,Ambow Education Holding Ltd. American Deposito...,AMEX,Consumer Defensive,Education & Training Services,41.0,7064995.0,146242912.0,5968.0,0.004,-515000.0,1492000.0,1492000.0,1359000.0,865000.0,4284000.0,977000.0,112000.0,103000.0,NaN,103000.0,-127032.0,1359000.0,9357000.0,112000.0,2882066.0,2856376.0,0.472000,0.476000,1359000.0,1359000.0,1359000.0,1359000.0,1359000.0,6000.0,1365000.0,1150000.0,-342000.0,1492000.0,-1492000.0,NaN,NaN,103000.0,NaN,103000.0,112000.0,5073000.0,NaN,NaN,628000.0,4445000.0,1082000.0,3363000.0,3363000.0,5185000.0,4284000.0,9469000.0,9469000.0,NaN,57127524.0,57127524.0,2369000.0,9725000.0,6588000.0,11450000.0,5932000.0,6588000.0,6525000.0,8250000.0,10950000.0,8250000.0,8250000.0,-128000.0,-128000.0,-508966000.0,517185000.0,159000.0,159000.0,0.0,12546000.0,7609000.0,167000.0,NaN,NaN,7442000.0,4742000.0,2700000.0,4937000.0,69000.0,262000.0,262000.0,2283000.0,500000.0,500000.0,2323000.0,713000.0,1610000.0,1000.0,1000.0,1609000.0,20796000.0,9927000.0,630000.0,NaN,NaN,1662000.0,1662000.0,NaN,7296000.0,-252000.0,7548000.0,235000.0,5312000.0,537000.0,0.0,10869000.0,NaN,2566000.0,NaN,2288000.0,-607000.0,2895000.0,831000.0,831000.0,-850000.0,NaN,-1176000.0,1676000.0,-987000.0,168000.0,17000.0,8091000.0,8441000.0,0.0,-350000.0,500000.0,500000.0,NaN,NaN,NaN,NaN,500000.0,500000.0,NaN,NaN,NaN,-987000.0,-987000.0,NaN,NaN,NaN,-787000.0,-787000.0,NaN,137000.0,137000.0,-913000.0,NaN,327000.0,-900000.0,-987000.0,87000.0,98000.0,-11000.0,-11000.0,89000.0,89000.0,-1492000.0,154000.0,164000.0,NaN,NaN,NaN,865000.0,865000.0,NaN,NaN,1359000.0,NaN,NaN,NaN,1783000.0,NaN,NaN,NaN,NaN,NaN,249000.0,815000.0,NaN,NaN,NaN,1464000.0,132000.0,586000.0,NaN,NaN,NaN,-200000.0,-200000.0,NaN,NaN,NaN,NaN,-598000.0,NaN,NaN,NaN,NaN,7260000.0,80000.0,NaN,NaN,NaN,-80000.0,NaN,NaN,50000.0,50000.0,NaN,NaN,NaN

We lost 138 columns. This is substantial, but still within the expected range

### **3.5 Drop Prefix from Column Names**

In [23]:
clean_financials_df.columns = (
    clean_financials_df.columns
    .str.replace("Income_", "", regex=False)
    .str.replace("Balance_", "", regex=False)
    .str.replace("CashFlow_", "", regex=False)
)

clean_financials_df.head()

,Symbol,Company Name,Exchange,Sector,Industry,Employees,MarketCap,EnterpriseValue,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Total Unusual Items,Total Unusual Items Excluding Goodwill,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,Net Interest Income,Interest Expense,Interest Income,Normalized Income,Net Income From Continuing And Discontinued Operation,Total Expenses,Total Operating Income As Reported,Diluted Average Shares,Basic Average Shares,Diluted EPS,Basic EPS,Diluted NI Availto Com Stockholders,Net Income Common Stockholders,Net Income,Net Income Including Noncontrolling Interests,Net Income Continuous Operations,Tax Provision,Pretax Income,Other Income Expense,Other Non Operating Income Expenses,Special Income Charges,Other Special Charges,Impairment Of Capital Assets,Gain On Sale Of Security,Net Non Operating Interest Income Expense,Interest Expense Non Operating,Interest Income Non Operating,Operating Income,Operating Expense,Depreciation Amortization Depletion Income Statement,Depreciation And Amortization In Income Statement,Research And Development,Selling General And Administration,Selling And Marketing Expense,General And Administrative Expense,Other Gand A,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,Common Stock Equity,Total Capitalization,Total Equity Gross Minority Interest,Stockholders Equity,Gains Losses Not Affecting Retained Earnings,Other Equity Adjustments,Retained Earnings,Additional Paid In Capital,Capital Stock,Common Stock,Preferred Stock,Total Liabilities Net Minority Interest,Total Non Current Liabilities Net Minority Interest,Other Non Current Liabilities,Non Current Deferred Liabilities,Non Current Deferred Taxes Liabilities,Long Term Debt And Capital Lease Obligation,Long Term Capital Lease Obligation,Long Term Debt,Current Liabilities,Other Current Liabilities,Current Deferred Liabilities,Current Deferred Revenue,Current Debt And Capital Lease Obligation,Current Debt,Other Current Borrowings,Payables And Accrued Expenses,Current Accrued Expenses,Payables,Total Tax Payable,Income Tax Payable,Accounts Payable,Total Assets,Total Non Current Assets,Other Non Current Assets,Non Current Deferred Assets,Non Current Deferred Taxes Assets,Goodwill And Other Intangible Assets,Other Intangible Assets,Goodwill,Net PPE,Accumulated Depreciation,Gross PPE,Leases,Other Properties,Machinery Furniture Equipment,Properties,Current Assets,Other Current Assets,Receivables,Taxes Receivable,Accounts Receivable,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Cash And Cash Equivalents,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Capital Expenditure,Interest Paid Supplemental Data,Income Tax Paid Supplemental Data,End Cash Position,Beginning Cash Position,Effect Of Exchange Rate Changes,Changes In Cash,Financing Cash Flow,Cash Flow From Continuing Financing Activities,Net Other Financing Charges,Proceeds From Stock Option Exercised,Net Common Stock Issuance,Common Stock Payments,Net Issuance Payments Of Debt,Net Short Term Debt Issuance,Net Long Term Debt Issuance,Long Term Debt Payments,Long Term Debt Issuance,Investing Cash Flow,Cash Flow From Continuing Investing Activities,Net Business Purchase And Sale,Sale Of Business,Purchase Of Business,Net PPE Purchase And Sale,Purchase Of PPE,Capital Expenditure Reported,Operating Cash Flow,Cash Flow From Continuing Operating Activities,Change In Working Capital,Change In Other Working Capital,Change In Other Current Assets,Change In Payables And Accrued Expense,Change In Accrued Expense,Change In Payable,Change In Account Payable,Change In Tax Payable,Change In Income Tax Payable,Change In Receivables,Changes In Account Receivables,Other Non Cash Items,Stock Based Compensation,Provisionand Write Offof Assets,Asset Impairment Charge,Deferred Tax,Deferred Income Tax,Depreciation Amortization Depletion,Depreciation And Amortization,Operating Gains Losses,Gain Loss On Investment Securities,Net Income From Continuing Operations,Restructuring And Mergern Acquisition,Minority Interest,Treasury Stock,Current Capital Lease Obligation,Pensionand Other Post Retirement Benefit Plans Current,Buildings And Improvements,Cash Financial,Issuance Of Capital Stock,Common Stock Issuance,Change In Prepaid Assets,Depreciation,Minority Interests,Other Operating Expenses,Other Payable,Construction In Progress,Prepaid Assets,Other Receivables,Net Other Investing Changes,Net Investment Purchase And Sale,Sale Of Investment,Net Intangibles Purchase And Sale,Purchase Of Intangibles,Earnings Losses From Equity Investments,Cash Dividends Paid,Common Stock Dividend Paid,Sale Of PPE,Change In Other Current Liabilities,Gain Loss On Sale Of PPE,Non Current Deferred Revenue,Interest Payable,Land And Improvements,Restricted Cash,Inventory,Finished Goods,Work In Process,Raw Materials,Change In Inventory,Other Short Term Investments,Purchase Of Investment,Amortization Cash Flow,Amortization Of Intangibles,Salaries And Wages,Investments And Advances,Long Term Equity Investment
0,ACCS,ACCESS Newswire Inc. Common Stock,AMEX,Communication Services,Advertising Agencies,91.0,24535150.0,24346960.0,-67650.0,0.205,1372000.0,-330000.0,-330000.0,-1558000.0,2993000.0,4999000.0,1042000.0,-1951000.0,-2000.0,2000.0,NaN,-1295650.0,4291000.0,24240000.0,-1871000.0,3859000.0,3858000.0,1.110000,1.110000,4291000.0,4291000.0,4291000.0,4291000.0,-1558000.0,-395000.0,-1953000.0,-330000.0,NaN,-250000.0,NaN,250000.0,-80000.0,-2000.0,2000.0,NaN,-1621000.0,18935000.0,2687000.0,2687000.0,2692000.0,13556000.0,6405000.0,7151000.0,7151000.0,17314000.0,5305000.0,22619000.0,22619000.0,NaN,3850435.0,3850435.0,NaN,2873000.0,999000.0,32901000.0,-1116000.0,999000.0,317000.0,30345000.0,32031000.0,30345000.0,30345000.0,-96000.0,-96000.0,5432000.0,25005000.0,4000.0,4000.0,0.0,11647000.0,2109000.0,20000.0,86000.0,86000.0,2003000.0,317000.0,1686000.0,9538000.0,NaN,5265000.0,5265000.0,870000.0,870000.0,870000.0,3403000.0,1769000.0,1634000.0,133000.0,133000.0,1501000.0,41992000.0,33570000.0,73000.0,3691000.0,3691000.0,29346000.0,10303000.0,19043000.0,460000.0,-669000.0,1129000.0,705000.0,324000.0,100000.0,0.0,8422000.0,1513000.0,3884000.0,NaN,3884000.0,-1336000.0,5220000.0,3025000.0,3025000.0,366000.0,-163000.0,-13391000.0,NaN,-192000.0,413000.0,2208000.0,3025000.0,4103000.0,110000.0,-1188000.0,-13554000.0,-13554000.0,NaN,NaN,-163000.0,-163000.0,-13391000.0,NaN,-13391000.0,-13391000.0,NaN,11808000.0,11808000.0,12000000.0,12000000.0,NaN,-20000.0,-20000.0,-172000.0,558000.0,558000.0,-531000.0,208000.0,512000.0,-171000.0,-401000.0,230000.0,154000.0,76000.0,76000.0,-1080000.0,-1080000.0,17000.0,909000.0,1335000.0,250000.0,188000.0,188000.0,2993000.0,2993000.0,-8894000.0,80000.0,4291000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGIG,Abundia Global Impact Group Inc. Common stock,AMEX,Utilities,Utilities - Renewable,2.0,51506696.0,40063780.0,0.0,0.000,-13714909.0,-14900411.0,-14900411.0,-29452289.0,220016.0,430118.0,-28615320.0,-28835336.0,-3942229.0,625599.0,25370.0,-14551878.0,-29452289.0,11028927.0,-28747387.0,32847237.0,32847237.0,-0.900000,-0.900000,-29452289.0,-29452289.0,-29452289.0,-29460935.0,-29460935.0,0.0,-29460935.0,-14900411.0,NaN,-14929660.0,13270632.0,544028.0,29249.0,-3942229.0,625599.0,25370.0,-10618295.0,10598809.0,NaN,NaN,752287.0,10584333.0,NaN,10584333.0,10584333.0,-19486.0,430118.0,410632.0,410632.0,NaN,36918281.0,36918281.0,5610215.0,10389975.0,4629972.0,29243253.0,-1043785.0,4629972.0,161139.0,19014417.0,25274691.0,19014417.0,19014417.0,-5314.0,-5314.0,-46055127.0,65037940.0,36918.0,36918.0,NaN,12841012.0,6439464.0,NaN,NaN,NaN,6407216.0,146942.0,6260274.0,6401548.0,NaN,NaN,NaN,3982759.0,3968562.0,NaN,2418789.0,NaN,2418789.0,NaN,NaN,2175672.0,31855429.0,26497666.0,12286.0,NaN,NaN,14384445.0,1398295.0,12986150.0,8733660.0,-627816.0,9361476.0,NaN,8730646.0,NaN,NaN,5357763.0,179209.0,56925.0,NaN,56925.0,NaN,NaN,4618621.0,4618621.0,-18098917.0,NaN,-6444139.0,13310972.0,-10046859.0,NaN,NaN,4618621.0,525809.0,63613.0,4029199.0,15177110.0,15177110.0,NaN,NaN,8310277.0,NaN,6866833.0,3935000.0,2931833.0,-5994139.0,8925972.0,-3095853.0,-3095853.0,NaN,NaN,NaN,-8660829.0,-8660829.0,NaN,-8052058.0,-8052058.0,1326843.0,NaN,86805.0,1070681.0,433561.0,637120.0,421359.0,NaN,NaN,181405.0,-24019.0,15846013.0,NaN,0.0,1659028.0,NaN,NaN,220016.0,209065.0,2356977.0,-45965.0,-29460935.0,NaN,0.0,NaN,14197.0,NaN,NaN,NaN,8310277.0,8310277.0,-12048.0,NaN,8646.0,-737811.0,243117.0,630830.0,503008.0,NaN,NaN,6951006.0,6951006.0,-1386030.0,-1386030.0,1522563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AIB,"BlockchAIn Digital Infrastructure, Inc Common ...",AMEX,Technology,Software - Application,3.0,135902528.0,113278776.0,0.0,0.000,-103195.0,67714.0,67714.0,-835431.0,862305.0,15001351.0,-35481.0,-897786.0,NaN,NaN,NaN,-903145.0,-835431.0,19414398.0,-897786.0,37646133.0,37646133.0,-0.022192,-0.022192,-835431.0,-835431.0,-835431.0,-835431.0,-835431.0,NaN,-835431.0,62355.0,-5359.0,67714.0,NaN,NaN,NaN,NaN,NaN,NaN,-897786.0,4413047.0,862305.0,862305.0,NaN,3550742.0,NaN,NaN,NaN,3515261.0,15001351.0,18516612.0,18516612.0,NaN,37646133.0,37646133.0,NaN,81712.0,3008145.0,7859281.0,-5258420.0,3008145.0,81712.0,7859281.0,7859281.0,7859281.0,7859281.0,NaN,NaN,7859281.0,0.0,0.0,0.0,0.0,9408235.0,680166.0,NaN,NaN,NaN,0.0,0.0,NaN,8728069.0,1845760.0,2330584.0,2330584.0,81712.0,NaN,NaN,4470013.0,NaN,4470013.0,NaN,NaN,3304012.0,17267516.0,13797867.0,NaN,NaN,NaN,4851136.0,NaN,4851136.0,8946731.0,-1495908.0,10442639.0,2846345.0,7423705.0,172589.0,0.0,3469649.0,218698.0,3235686.0,NaN,2152226.0,NaN,NaN,15265.0,15265.0,2297032.0,NaN,NaN,NaN,-38927.0,NaN,NaN,15265.0,131107.0,NaN,-115842.0,-2506729.0,-2506729.0,-485833.0,NaN,3889834.0,NaN,-18750.0,-18750.0,NaN,NaN,NaN,54928.0,54928.0,NaN,NaN,NaN,93073.0,-38927.0,NaN,2335959.0,2335959.0,2376799.0,664004.0,-158627.0,1448123.0,NaN,NaN,NaN,NaN,NaN,-1422460.0,-1422460.0,NaN,NaN,NaN,NaN,NaN,NaN,862305.0,862305.0,-67714.0,NaN,-835431.0,NaN,NaN,NaN,81712.0,NaN,NaN,15265.0,3889834.0,3889834.0,NaN,NaN,NaN,NaN,1166001.0,NaN,NaN,NaN,-38145.0,NaN,NaN,NaN,NaN,NaN,-5891980.0,-5891980.0,132000.0,1845759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AIRI,Air Industries Group Common Stock,AMEX,Industrials,Aerospace & Defense,160.0,14746000.0,46463012.0,0.0,0.091,3777000.0,NaN,NaN,-1305000.0,3372000.0,39734000.0,3777000.0,405000.0,-1841000.0,1841000.0,NaN,-1305000.0,-1305000.0,48259000.0,-338000.0,4216918.0,4216918.0,-0.310000,-0.310000,-1305000.0,-1305000.0,-1305000.0,-1305000.0,-1305000.0,-131000.0,-1436000.0,743000.0,743000.0,NaN,NaN,NaN,NaN,-1841000.0,1841000.0,NaN,-338000.0,8525000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8187000.0,39734000.0,47921000.0,47921000.0,NaN,4776454.0,4776454.0,29424000.0,30806000.0,19201000.0,49305000.0,9168000.0,19201000.0,702000.0,19201000.0,20713000.0,19201000.0,19201000.0,NaN,NaN,-70412000.0,89608000.0,5000.0,5000.0,0.0,39128000.0,1512000.0,NaN,0.0,NaN,1512000.0,0.0,1512000.0,37616000.0,NaN,419000.0,419000.0,29294000.0,28592000.0,28592000.0,7903000.0,803000.0,7100000.0,NaN,NaN,7100000.0,58329000.0,11545000.0,614000.0,NaN,NaN,NaN,NaN,NaN,10931000.0,-39201000.0,50132000.0,1139000.0,17708000.0,28233000.0,0.0,46784000.0,766000.0,7071000.0,NaN,7071000.0,-464000.0,7535000.0,680000.0,680000.0,-4674000.0,NaN,-2533000.0,6353000.0,-3322000.0,1829000.0,21000.0,4610000.0,753000.0,NaN,3857000.0,8331000.0,8331000.0,-127000.0,NaN,4638000.0,NaN,3820000.0,5343000.0,-1523000.0,-1523000.0,0.0,-3122000.0,-3122000.0,NaN,NaN,NaN,-3122000.0,-3322000.0,NaN,-1352000.0,-1352000.0,-4496000.0,-724000.0,NaN,888000.0,NaN,NaN,NaN,NaN,NaN,2057000.0,1761000.0,69000.0,1047000.0,68000.0,NaN,NaN,NaN,3372000.0,3372000.0,-107000.0,-39000.0,-1305000.0,NaN,NaN,NaN,702000.0,0.0,2739000.0,680000.0,4638000.0,4638000.0,-386000.0,3372000.0,NaN,8525000.0,NaN,NaN,76000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.0,-881000.0,-68000.0,0.0,NaN,313000.0,3930000.0,34261000.0,677000.0,26278000.0,7306000.0,-5450000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AMBO,Ambow Education Holding Ltd. American Deposito...,AMEX,Consumer Defensive,Education & Training Services,41.0,7064995.0,146242912.0,5968.0,0.004,-515000.0,1492000.0,1492000.0,1359000.0,865000.0,4284000.0,977000.0,112000.0,103000.0,NaN,103000.0,-127032.0,1359000.0,9357000.0,112000.0,2882066.0,2856376.0,0.472000,0.476000,1359000.0,1359000.0,1359000.0,1359000.0,1359000.0,6000.0,1365000.0,1150000.0,-342000.0,1492000.0,-1492000.0,NaN,NaN,103000.0,NaN,103000.0,112000.0,5073000.0,NaN,NaN,628000.0,4445000.0,1082000.0,3363000.0,3363000.0,5185000.0,4284000.0,9469000.0,9469000.0,NaN,57127524.0,57127524.0,2369000.0,9725000.0,6588000.0,11450000.0,5932000.0,6588000.0,6525000.0,8250000.0,10950000.0,8250000.0,8250000.0,-128000.0,-128000.0,-508966000.0,517185000.0,159000.0,159000.0,0.0,12546000.0,7609000.0,167000.0,NaN,NaN,7442000.0,4742000.0,2700000.0,4937000.0,69000.0,262000.0,262000.0,2283000.0,500000.0,500000.0,2323000.0,713000.0,1610000.0,1000.0,1000.0,1609000.0,20796000.0,9927000.0,630000.0,NaN,NaN,1662000.0,1662000.0,NaN,7296000.0,-252000.0,7548000.0,235000.0,5312000.0,537000.0,0.0,10869000.0,NaN,2566000.0,NaN,2288000.0,-607000.0,2895000.0,831000.0,831000.0,-850000.0,NaN,-1176000.0,1676000.0,-987000.0,168000.0,17000.0,8091000.0,8441000.0,0.0,-350000.0,500000.0,500000.0,NaN,NaN,NaN,NaN,500000.0,500000.0,NaN,NaN,NaN,-987000.0,-987000.0,NaN,NaN,NaN,-787000.0,-787000.0,NaN,137000.0,137000.0,-913000.0,NaN,327000.0,-900000.0,-987000.0,87000.0,98000.0,-11000.0,-11000.0,89000.0,89000.0,-1492000.0,154000.0,164000.0,NaN,NaN,NaN,865000.0,865000.0,NaN,NaN,1359000.0,NaN,NaN,NaN,1783000.0,NaN,NaN,NaN,NaN,NaN,249000.0,815000.0,NaN,NaN,NaN,1464000.0,132000.0,586000.0,NaN,NaN,NaN,-200000.0,-200000.0,NaN,NaN,NaN,NaN,-598000.0,NaN,NaN,NaN,NaN,7260000.0,80000.0,NaN,NaN,NaN,-80000.0,NaN,NaN,50000.0,50000.0,NaN,NaN,NaN

# **4. Final Check**

In [24]:
print(f"Final dataset shape: {clean_financials_df.shape}")
print(f"Remaining missing values: {clean_financials_df.isna().sum().sum():,}")

clean_financials_df.isna().mean().sort_values(ascending=False).head(20)

Final dataset shape: (4576, 222)
Remaining missing values: 304,127

Change In Income Tax Payable               0.796547
Change In Tax Payable                      0.796547
Non Current Deferred Revenue               0.786276
Interest Payable                           0.786058
Earnings Losses From Equity Investments    0.776442
Purchase Of Intangibles                    0.774257
Long Term Equity Investment                0.763986
Net Intangibles Purchase And Sale          0.757430
Other Special Charges                      0.757212
Capital Expenditure Reported               0.749344
Sale Of Business                           0.743663
Salaries And Wages                         0.741259
Work In Process                            0.740822
Cash Financial                             0.739073
Other Payable                              0.734266
Taxes Receivable                           0.733173
Restricted Cash                            0.719187
Impairment Of Capital Assets               0.717657
Other Operating Expenses                   0.698427
Net Short Term Debt Issuance               0.696023
dtype: float64

In [25]:
output_path = INTERIM_DATA_DIR / "clean_financials_with_metadata.xlsx"

clean_financials_df.to_excel(output_path, index=False)

print(f"Cleaned dataset saved to: {output_path}")

Cleaned dataset saved to: C:\Users\semoy\OneDrive\Documentos\GitHub\financial_kpi_clustering\data\interim\clean_financials_with_metadata.xlsx

# Notebook Summary

This notebook cleaned and prepared the structured financial dataset generated in Notebook 1 for downstream KPI engineering and clustering analysis.

The process began by loading the financial statement dataset enriched with company metadata, including sector, industry, employee count, market capitalisation, enterprise value, and currency. Initial validation was performed to inspect dataset size, column structure, missing values, and financial feature coverage.

Sparse financial features were removed using a missing-value threshold, ensuring that the retained variables have sufficient coverage across the company universe. Constant or non-informative columns were also identified and removed to reduce noise in later analysis. Metadata fields were retained where they provide useful context for sector-level segmentation and cluster interpretation.

Finally, financial statement prefixes were removed from column names to improve readability, and the cleaned dataset was exported for use in Notebook 3. The resulting dataset provides a more reliable foundation for KPI engineering, feature scaling, dimensionality reduction, and clustering experiments.